import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { executeCapability, executionCoordinatorDiagnostics, type ExecutionRequest } from '../capability-execution-coordinator.js'

const request: ExecutionRequest = { capabilityPlanId: 'plan-1', contextSessionId: 'context-1', providerId: 'provider-1', capabilityId: 'read', operation: 'read', requestIdentity: { requestedBy: 'test', requestedAt: new Date().toISOString() } }
const provider = { providerId: 'provider-1', providerType: 'capability', enabled: true, registrationState: 'enabled', health: 'healthy', capabilities: ['read'], manifestIdentity: { digest: 'a'.repeat(64) } } as never
const plan = { planId: 'plan-1', contextSessionId: 'context-1', sourceIds: [], providerId: 'provider-1', capabilityId: 'read', requestedOperation: 'read', capabilityManifestDigest: 'a'.repeat(64), requiredPermissions: [], requiredBudgets: { maximumBytes: 0, maximumDurationMs: 0, maximumQueries: 0 }, grantBinding: { grantId: 'grant-1', grantVersion: 1, permissionDigest: '4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945', budgetDigest: '1e4168c357816789417b7732f260dcf98869524d4fb33c44287598fd0d533320' }, approvalState: 'approved', validity: 'valid', expiresAt: new Date(Date.now() + 60_000).toISOString() } as never
const grant = { grantId: 'grant-1', grantVersion: 1, state: 'active', permissions: [], budgets: { maximumBytes: 0, maximumDurationMs: 0, maximumQueries: 0 } } as never
const adapter = { adapterId: 'test-adapter', supportedProviderTypes: ['capability'] as ('capability')[], capabilityTypes: ['*'], healthCheck: () => ({ available: true, detail: 'test' }), validate: () => ({ valid: true, detail: 'test' }), dispatch: () => ({ executed: false as const, reason: 'execution_not_implemented' as const }), executeApproved: async (_request: unknown, _auth: unknown) => ({ status: 'completed' as const, output: { ok: true }, metadata: { providerId: 'provider-1', capabilityId: 'read', operation: 'read', durationMs: 1 }, errors: [], evidence: [], auditReferences: { executionId: 'adapter-execution-1', dispatchId: 'dispatch-1', validationId: 'validation-1' } }) }

test('fails closed before dispatch when validation state is incomplete', async () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'workbench-coordinator-')); try { const result = await executeCapability(request, { plan, provider, validationState: {} }, { rootDir: root, adapters: [adapter] }); assert.equal(result.ok, true); if (result.ok) assert.equal(result.value.lifecycleState, 'failed') } finally { fs.rmSync(root, { recursive: true, force: true }) } })
test('coordinates validation, dispatch, adapter execution, and reconciliation', async () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'workbench-coordinator-')); try { const result = await executeCapability(request, { plan, provider, validationState: { context: { sessionId: 'context-1', status: 'confirmed', sourceIds: [] }, provider, grant, advertisedCapabilities: ['read'] } }, { rootDir: root, adapters: [adapter] }); assert.equal(result.ok, true); if (result.ok) { assert.equal(result.value.lifecycleState, 'completed'); assert.equal(result.value.result?.metadata.providerId, 'provider-1'); assert.ok(result.value.dispatchId); assert.ok(result.value.validationId) } } finally { fs.rmSync(root, { recursive: true, force: true }) } })
test('reports adapter availability and terminal diagnostics', async () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'workbench-coordinator-')); try { await executeCapability(request, { plan, provider, validationState: {} }, { rootDir: root, adapters: [adapter] }); const diagnostics = executionCoordinatorDiagnostics({ rootDir: root, adapters: [adapter] }); assert.equal(diagnostics.failed.length, 1); assert.equal(diagnostics.adapterAvailability[0]?.available, true) } finally { fs.rmSync(root, { recursive: true, force: true }) } })
