import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { initializeCapabilityRuntime } from '../capability-runtime-bootstrap.js'
import { getCapabilityRuntimeDiagnostic } from '../capability-runtime-diagnostics.js'
import { persistKnowledgeContextRuntimeStatus } from '../knowledge-context-runtime.js'

const adapter = { adapterId: 'unavailable', supportedProviderTypes: ['capability'] as ('capability')[], capabilityTypes: ['*'], healthCheck: () => ({ available: false, detail: 'offline' }), validate: () => ({ valid: true, detail: 'ok' }), dispatch: () => ({ executed: false as const, reason: 'execution_not_implemented' as const }) }
test('produces stable bounded warning diagnostics for unavailable adapters', () => { const rootDir = fs.mkdtempSync(path.join(os.tmpdir(), 'workbench-runtime-diagnostics-')); try { const options = { rootDir, adapters: [adapter] }; initializeCapabilityRuntime(options); persistKnowledgeContextRuntimeStatus({ initialized: true, readiness: 'warning', enabledProviders: ['z-provider', 'a-provider'], availableProviders: ['a-provider'], providerCount: 2, providers: [{ providerId: 'a-provider', registryHealth: 'healthy', available: true, indexReady: true, indexGeneration: 2 }, { providerId: 'z-provider', registryHealth: 'unavailable', available: false, indexReady: false, indexGeneration: 0, failure: 'offline' }], retrievalReady: true, lastInitializedAt: '2026-01-01T00:00:00.000Z', retrievalFailures: 1, warnings: ['z-provider: offline'], failedProviders: [{ providerId: 'z-provider', reason: 'offline' }] }, { registry: { rootDir } }); const first = getCapabilityRuntimeDiagnostic(options); const second = getCapabilityRuntimeDiagnostic(options); assert.ok(first); assert.deepEqual(first, second); assert.equal(first?.schemaVersion, 1); assert.equal(first?.health.adapterAvailability[0]?.available, false); assert.equal(first?.knowledgeRuntime?.readiness, 'warning'); assert.equal(first?.lifecycle.readiness, 'warning'); assert.ok(first?.warnings.includes('Knowledge context runtime is degraded.')); assert.ok(Buffer.byteLength(JSON.stringify(first), 'utf8') < 32_000) } finally { fs.rmSync(rootDir, { recursive: true, force: true }) } })
test('reports failed bootstrap as unavailable with remediation', () => { const rootDir = fs.mkdtempSync(path.join(os.tmpdir(), 'workbench-runtime-diagnostics-')); try { fs.writeFileSync(path.join(rootDir, 'workbench-capability-executions.json'), '{bad'); const options = { rootDir, adapters: [] }; initializeCapabilityRuntime(options); const diagnostic = getCapabilityRuntimeDiagnostic(options); assert.equal(diagnostic?.lifecycle.readiness, 'unavailable'); assert.ok(diagnostic?.remediation.some(item => item.code === 'runtime_recovery_failed')) } finally { fs.rmSync(rootDir, { recursive: true, force: true }) } })
