import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { dispatchCapability, dispatchDiagnostics, listDispatchAudit, type CapabilityAdapter, type DispatchRequest } from '../capability-dispatch.js'
import type { CapabilityPlan } from '../capability-planning.js'
import type { ExecutionValidationResult } from '../capability-pre-execution.js'
import type { ProviderInventoryRecord } from '../provider-inventory.js'

function fixture(): { root: string; cleanup: () => void } { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'workbench-dispatch-')); return { root, cleanup: () => fs.rmSync(root, { recursive: true, force: true }) } }
const provider: ProviderInventoryRecord = { providerId: 'provider.one', providerType: 'capability', displayName: 'Provider', manifestIdentity: { manifestVersion: 1, digest: 'a'.repeat(64), providerVersion: '1.0.0', contractVersion: '1' }, location: { kind: 'opaque-reference', value: 'provider:one' }, enabled: true, health: 'healthy', discoverySource: 'test', capabilities: ['repository.read'], ownership: { ownerType: 'user', ownerId: 'owner' }, lastValidationTime: '2026-08-23T00:00:00.000Z', registrationState: 'enabled' }
const plan: CapabilityPlan = { planId: 'plan-1', contextSessionId: 'session-1', sourceIds: ['repo'], providerId: 'provider.one', capabilityId: 'repository.read', capabilityManifestDigest: 'a'.repeat(64), selectedCandidateReason: 'exact', requestedOperation: 'read repository', requiredPermissions: ['read'], requiredBudgets: { maximumBytes: 10, maximumDurationMs: 10, maximumQueries: 1 }, riskClassification: 'low', expiresAt: '2026-08-23T05:00:00.000Z', approvalState: 'approved', validity: 'valid', auditIdentity: { resolutionId: 'resolution-1', grantId: 'grant-1', createdAt: '2026-08-23T00:00:00.000Z', createdBy: 'test' }, grantBinding: { grantId: 'grant-1', grantVersion: 1, permissionDigest: 'b'.repeat(64), budgetDigest: 'c'.repeat(64) } }
const validation: ExecutionValidationResult = { validationId: 'validation-1', outcome: 'allowed', allowed: true, reasons: [], evidence: [], expiresAt: '2026-08-23T05:00:00.000Z', auditIdentity: { validationId: 'validation-1', planId: 'plan-1', occurredAt: '2026-08-23T03:00:00.000Z' } }
const request: DispatchRequest = { capabilityPlanId: 'plan-1', validationId: 'validation-1', providerId: 'provider.one', capabilityId: 'repository.read', requestedOperation: 'read repository', contextSessionId: 'session-1', auditIdentity: { requestedBy: 'test', requestedAt: '2026-08-23T03:00:00.000Z' } }
const adapter: CapabilityAdapter = { adapterId: 'future-generic-adapter', supportedProviderTypes: ['capability'], capabilityTypes: ['repository.read'], healthCheck: () => ({ available: true, detail: 'placeholder adapter healthy' }), validate: () => ({ valid: true, detail: 'placeholder validation passed' }), dispatch: () => ({ executed: false, reason: 'execution_not_implemented' }) }

test('accepts only a validated request and reaches dispatch_ready without invoking the adapter', () => {
  const f = fixture(); try { let invoked = false; const safeAdapter = { ...adapter, dispatch: () => { invoked = true; return { executed: false as const, reason: 'execution_not_implemented' as const } } }; const result = dispatchCapability(request, { plan, validation, provider, adapters: [safeAdapter] }, { rootDir: f.root }); assert.equal(result.ok, true); if (result.ok) { assert.equal(result.value.status, 'accepted'); assert.equal(result.value.adapterId, 'future-generic-adapter') }; assert.equal(invoked, false); const audit = listDispatchAudit({ rootDir: f.root }); assert.equal(audit.ok, true); if (audit.ok) assert.deepEqual(audit.value.map(event => event.eventType), ['dispatch_requested', 'validation_checked', 'adapter_selected', 'dispatch_ready']) } finally { f.cleanup() }
})

test('rejects missing, denied, stale, changed, policy-blocked, and adapter-missing requests', () => {
  const f = fixture(); try { const missing = dispatchCapability(request, { plan, adapters: [] }, { rootDir: f.root }); assert.equal(missing.ok, true); if (missing.ok) assert.equal(missing.value.rejectionReason, 'missing_validation'); const denied = dispatchCapability(request, { plan, validation: { ...validation, allowed: false, outcome: 'denied', reasons: ['permission_denied'] }, provider, adapters: [adapter] }, { rootDir: f.root }); assert.equal(denied.ok, true); if (denied.ok) assert.equal(denied.value.rejectionReason, 'validation_denied'); const changed = dispatchCapability(request, { plan, validation, provider: { ...provider, providerId: 'other' }, adapters: [adapter] }, { rootDir: f.root }); assert.equal(changed.ok, true); if (changed.ok) assert.equal(changed.value.rejectionReason, 'provider_changed'); const blocked = dispatchCapability(request, { plan, validation, provider, adapters: [adapter], policyAllowed: false }, { rootDir: f.root }); assert.equal(blocked.ok, true); if (blocked.ok) assert.equal(blocked.value.rejectionReason, 'dispatch_policy_denied'); const noAdapter = dispatchCapability(request, { plan, validation, provider, adapters: [] }, { rootDir: f.root }); assert.equal(noAdapter.ok, true); if (noAdapter.ok) assert.equal(noAdapter.value.rejectionReason, 'missing_adapter'); const diagnostics = dispatchDiagnostics({ rootDir: f.root }); assert.equal(diagnostics.ok, true); if (diagnostics.ok) assert.ok(diagnostics.value.rejected.length >= 1) } finally { f.cleanup() }
})
