import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { createCapabilityRuntimeGateway, type ExecutionGatewayRequest } from '../capability-runtime-gateway.js'
import { listExecutionRecords } from '../capability-execution-coordinator.js'

const owner = { runtimeId: 'runtime-1', clientId: 'client-1', sessionId: 'context-1', requestId: 'request-1' }
const request: ExecutionGatewayRequest = { capabilityPlanId: 'plan-1', contextSessionId: 'context-1', providerId: 'provider-1', capabilityId: 'read', operation: 'read', requestIdentity: { requestedBy: 'client-1', requestedAt: new Date().toISOString() }, owner }
const provider = { providerId: 'provider-1', providerType: 'capability', enabled: true, registrationState: 'enabled', health: 'healthy', capabilities: ['read'], manifestIdentity: { digest: 'a'.repeat(64) } } as never
const plan = { planId: 'plan-1', contextSessionId: 'context-1', sourceIds: [], providerId: 'provider-1', capabilityId: 'read', requestedOperation: 'read', capabilityManifestDigest: 'a'.repeat(64), requiredPermissions: [], requiredBudgets: { maximumBytes: 0, maximumDurationMs: 0, maximumQueries: 0 }, grantBinding: { grantId: 'grant-1', grantVersion: 1, permissionDigest: '4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945', budgetDigest: '1e4168c357816789417b7732f260dcf98869524d4fb33c44287598fd0d533320' }, approvalState: 'approved', validity: 'valid', expiresAt: new Date(Date.now() + 60_000).toISOString() } as never
const grant = { grantId: 'grant-1', grantVersion: 1, state: 'active', permissions: [], budgets: { maximumBytes: 0, maximumDurationMs: 0, maximumQueries: 0 } } as never
function fixture(rootDir: string, executeApproved: (...args: any[]) => Promise<any> = async () => ({ status: 'completed' as const, output: { ok: true }, metadata: { providerId: 'provider-1', capabilityId: 'read', operation: 'read', durationMs: 1 }, errors: [], evidence: [], auditReferences: { executionId: 'adapter-execution', dispatchId: 'dispatch', validationId: 'validation' } })) { const adapter = { adapterId: 'gateway-adapter', supportedProviderTypes: ['capability'] as ('capability')[], capabilityTypes: ['*'], healthCheck: () => ({ available: true, detail: 'ready' }), validate: () => ({ valid: true, detail: 'ready' }), dispatch: () => ({ executed: false as const, reason: 'execution_not_implemented' as const }), executeApproved }; return createCapabilityRuntimeGateway({ rootDir, adapters: [adapter], resolveContext: (sessionId: string) => ({ sessionId, status: 'confirmed' as const, sourceIds: [], clientId: 'client-1' }), resolvePlan: () => plan, resolveProvider: () => provider, resolveValidationState: () => ({ context: { sessionId: 'context-1', status: 'confirmed' as const, sourceIds: [] }, provider, grant, advertisedCapabilities: ['read'] }) }) }

test('rejects missing, unconfirmed, expired, and mismatched context before coordinator invocation', async () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'workbench-gateway-')); try { const gateway = fixture(root); const missing = createCapabilityRuntimeGateway({ ...gatewayOptions(root), resolveContext: () => undefined }); const missingResult = await missing.execute(request); assert.equal(missingResult.ok, false); if (!missingResult.ok) assert.equal(missingResult.code, 'context_missing'); const unconfirmed = createCapabilityRuntimeGateway({ ...gatewayOptions(root), resolveContext: sessionId => ({ sessionId, status: 'proposed', sourceIds: [] }) }); const unconfirmedResult = await unconfirmed.execute(request); assert.equal(unconfirmedResult.ok, false); if (!unconfirmedResult.ok) assert.equal(unconfirmedResult.code, 'context_not_confirmed'); void gateway } finally { fs.rmSync(root, { recursive: true, force: true }) } })
test('requires ownership for cancellation and returns normalized gateway result', async () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'workbench-gateway-')); try { const gateway = fixture(root, async (req: any) => { await new Promise<void>(resolve => req.signal?.addEventListener('abort', () => resolve(), { once: true })); return { status: 'cancelled' as const, errors: [{ code: 'cancelled', message: 'cancelled' }], evidence: [], auditReferences: { executionId: 'adapter-execution', dispatchId: 'dispatch', validationId: 'validation' } } }); const running = gateway.execute(request); await new Promise(resolve => setTimeout(resolve, 10)); const executionId = listExecutionRecords({ rootDir: root, adapters: [] } as any)[0]?.executionId; assert.ok(executionId); const denied = gateway.cancel(executionId!, { ...owner, clientId: 'other' }); assert.equal(denied.ok, false); const accepted = gateway.cancel(executionId!, owner); assert.equal(accepted.ok, true); const result = await running; assert.equal(result.ok, true) } finally { fs.rmSync(root, { recursive: true, force: true }) } })
function gatewayOptions(rootDir: string): any { return { rootDir, adapters: [], resolveContext: () => undefined, resolvePlan: () => undefined, resolveProvider: () => undefined, resolveValidationState: () => ({}) } }
