import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { decideCapabilityProviderActivation, discoverCapabilityProviders, getCapabilityProviderDiagnostics, listCapabilityProviders, registerCapabilityProvider, requestCapabilityProviderActivation, transitionCapabilityProvider, type CapabilityProviderManifest } from '../capability-provider.js'

function fixture() { const rootDir = fs.mkdtempSync(path.join(os.tmpdir(), 'workbench-capability-provider-')); const manifest: CapabilityProviderManifest = { kind: 'workbench.capability-provider.manifest', manifestVersion: 1, providerId: 'fixture.tools', providerType: 'capability', displayName: 'Fixture tools', providerVersion: '1', location: { kind: 'opaque-reference', value: 'fixture://tools' }, ownership: { ownerType: 'user', ownerId: 'test-user' }, capabilities: ['metadata'], operations: [{ operationId: 'inspect', description: 'Inspect bounded metadata', permission: 'read', inputSchemaVersion: '1' }], health: { state: 'healthy', observedAt: '2026-08-24T00:00:00.000Z' }, compatibility: { contractVersion: '1' } }; return { rootDir, manifest, cleanup: () => fs.rmSync(rootDir, { recursive: true, force: true }) } }

test('discovers normalized MCP, CLI, skill, and orchestrator metadata without activation', () => { const f = fixture(); try { const inputs = (['mcp', 'cli', 'skill', 'orchestrator'] as const).map(source => ({ source, manifest: { ...f.manifest, providerId: `fixture.${source}` } })); const result = discoverCapabilityProviders(inputs); assert.equal(result.failures.length, 0); assert.deepEqual(result.candidates.map(item => item.providerId), ['fixture.cli', 'fixture.mcp', 'fixture.orchestrator', 'fixture.skill']); assert.deepEqual(getCapabilityProviderDiagnostics({ rootDir: f.rootDir }).activeProviderIds, []) } finally { f.cleanup() } })

test('registers, enables, and explicitly activates a capability provider', () => { const f = fixture(); try { const candidate = discoverCapabilityProviders([{ source: 'mcp', manifest: f.manifest }]).candidates[0]!; assert.equal(registerCapabilityProvider(candidate, { rootDir: f.rootDir }).ok, true); assert.equal(transitionCapabilityProvider('fixture.tools', 'reviewed', { rootDir: f.rootDir }).ok, true); assert.equal(transitionCapabilityProvider('fixture.tools', 'registered', { rootDir: f.rootDir }).ok, true); assert.equal(transitionCapabilityProvider('fixture.tools', 'enabled', { rootDir: f.rootDir }).ok, true); const request = requestCapabilityProviderActivation('fixture.tools', 'requester', 'session-1', { rootDir: f.rootDir }); assert.equal(request.ok, true); if (!request.ok) return; assert.deepEqual(getCapabilityProviderDiagnostics({ rootDir: f.rootDir }).activeProviderIds, []); const approved = decideCapabilityProviderActivation(request.value.activationId, true, 'approver', 'approved for bounded execution planning', { rootDir: f.rootDir }); assert.equal(approved.ok, true); const diagnostics = getCapabilityProviderDiagnostics({ rootDir: f.rootDir }); assert.deepEqual(diagnostics.activeProviderIds, ['fixture.tools']); assert.deepEqual(diagnostics.availableCapabilities, ['metadata']); assert.deepEqual(listCapabilityProviders({ rootDir: f.rootDir }).ok, true) } finally { f.cleanup() } })

test('rejects invalid capability manifests and never executes discovery inputs', () => { const invalid = discoverCapabilityProviders([{ source: 'cli', manifest: { providerId: 'bad' } as never }]); assert.equal(invalid.candidates.length, 0); assert.equal(invalid.failures[0]?.code, 'invalid_manifest') })
