import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { discoverProviderManifests } from '../provider-discovery.js'
import { discoverIntoProviderInventory, transitionProviderRegistration, type ProviderInventoryRecord } from '../provider-inventory.js'
import { resolveCapabilities } from '../capability-resolution.js'
import { createAndPersistCapabilityPlan, listCapabilityPlans, transitionCapabilityPlan, type CapabilityGrantSnapshot, type CapabilityPlan } from '../capability-planning.js'
import { getExecutionValidationAuditPath, validateAndAuditCapability, validateCapabilityBeforeExecution, validationDiagnostics } from '../capability-pre-execution.js'
import { listCapabilityAuditEvents } from '../capability-audit.js'

function fixture(): { root: string; cleanup: () => void } { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'workbench-pre-execution-')); return { root, cleanup: () => fs.rmSync(root, { recursive: true, force: true }) } }
function setup(root: string): { plan: CapabilityPlan; provider: ProviderInventoryRecord; grant: CapabilityGrantSnapshot } {
  const file = path.join(root, 'provider.json'); fs.writeFileSync(file, JSON.stringify({ kind: 'workbench.provider.manifest', manifestVersion: 1, providerId: 'provider.one', providerType: 'capability', displayName: 'Provider One', providerVersion: '1.0.0', location: { kind: 'opaque-reference', value: 'provider:one' }, ownership: { ownerType: 'user', ownerId: 'owner' }, capabilities: ['repository.read'], health: { state: 'healthy', observedAt: '2026-08-23T00:00:00.000Z' }, compatibility: { contractVersion: '1' } }))
  const options = { rootDir: root, now: () => new Date('2026-08-23T01:00:00.000Z') }; const discovered = discoverProviderManifests([{ path: file }], { now: () => '2026-08-23T00:30:00.000Z' }); const stored = discoverIntoProviderInventory(discovered, 'test', options); assert.equal(stored.ok, true); if (!stored.ok) throw new Error('inventory failed'); transitionProviderRegistration('provider.one', 'reviewed', options); transitionProviderRegistration('provider.one', 'registered', options); transitionProviderRegistration('provider.one', 'enabled', options)
  const provider = { ...stored.value[0], registrationState: 'enabled' as const, enabled: true }; const resolution = resolveCapabilities({ context: { sessionId: 'session-1', status: 'confirmed', sourceIds: ['repo'] }, intent: { query: 'read repository', requestedCapabilities: ['repository.read'] }, providers: [provider], now: '2026-08-23T02:00:00.000Z' }); const grant: CapabilityGrantSnapshot = { grantId: 'grant-1', grantVersion: 1, state: 'active', permissions: ['read'], budgets: { maximumBytes: 1000, maximumDurationMs: 1000, maximumQueries: 1 } }; const create = createAndPersistCapabilityPlan({ context: { sessionId: 'session-1', status: 'confirmed', sourceIds: ['repo'] }, resolution, providers: [provider], grants: [grant], requestedOperation: 'read repository', requiredPermissions: ['read'], requiredBudgets: { maximumBytes: 100, maximumDurationMs: 100, maximumQueries: 1 }, expiresAt: '2026-08-23T05:00:00.000Z', createdBy: 'test', now: '2026-08-23T02:00:00.000Z' }, options); assert.equal(create.ok, true); if (!create.ok) throw new Error('plan failed'); transitionCapabilityPlan(create.value.planId, 'reviewed', options); transitionCapabilityPlan(create.value.planId, 'approved', options); const plans = listCapabilityPlans(options); assert.equal(plans.ok, true); if (!plans.ok || !plans.value[0]) throw new Error('approved plan missing'); return { plan: plans.value[0], provider, grant }
}
function request(plan: CapabilityPlan, timestamp = '2026-08-23T03:00:00.000Z') { return { capabilityPlanId: plan.planId, contextSessionId: plan.contextSessionId, providerId: plan.providerId, capabilityId: plan.capabilityId, manifestDigest: plan.capabilityManifestDigest, requestedOperation: plan.requestedOperation, timestamp } }

test('allows an approved plan only when every pre-execution check passes', () => {
  const f = fixture(); try { const { plan, provider, grant } = setup(f.root); const result = validateCapabilityBeforeExecution(request(plan), { plan, context: { sessionId: 'session-1', status: 'confirmed', sourceIds: ['repo'] }, provider, grant }); assert.equal(result.outcome, 'allowed', JSON.stringify(result.reasons)); assert.equal(result.allowed, true); assert.equal(result.reasons.length, 0) } finally { f.cleanup() }
})

test('denies missing, expired, disabled, unhealthy, permission, budget, and policy failures explicitly', () => {
  const f = fixture(); try { const { plan, provider, grant } = setup(f.root); const result = validateCapabilityBeforeExecution(request(plan), { plan, context: { sessionId: 'session-1', status: 'expired', sourceIds: ['changed'] }, provider: { ...provider, enabled: false, registrationState: 'disabled', health: 'degraded' }, grant: { ...grant, state: 'revoked', permissions: [], budgets: { maximumBytes: 1, maximumDurationMs: 1, maximumQueries: 0 } }, operationAllowed: false, riskPolicy: { allowLowRisk: false, allowMediumRisk: false, allowHighRisk: false } }); assert.equal(result.outcome, 'invalidated'); assert.ok(result.reasons.includes('context_expired')); assert.ok(result.reasons.includes('provider_disabled')); assert.ok(result.reasons.includes('provider_unhealthy')); assert.ok(result.reasons.includes('grant_invalid')); assert.ok(result.reasons.includes('permission_denied')); assert.ok(result.reasons.includes('budget_exceeded')); assert.ok(result.reasons.includes('operation_not_allowed')) } finally { f.cleanup() }
})

test('invalidates changed manifest or capability and records audit diagnostics', () => {
  const f = fixture(); try { const { plan, provider, grant } = setup(f.root); const options = { rootDir: f.root }; const result = validateAndAuditCapability(request(plan), { plan, context: { sessionId: 'session-1', status: 'confirmed', sourceIds: ['repo'] }, provider: { ...provider, manifestIdentity: { ...provider.manifestIdentity, digest: 'f'.repeat(64) } }, grant, advertisedCapabilities: [] }, options); assert.equal(result.ok, true); if (result.ok) { assert.equal(result.value.outcome, 'invalidated'); assert.ok(result.value.reasons.includes('provider_changed')); assert.ok(result.value.reasons.includes('capability_unavailable')) }; assert.equal(fs.statSync(getExecutionValidationAuditPath(options)).mode & 0o077, 0); const diagnostics = validationDiagnostics(options); assert.equal(diagnostics.ok, true); if (diagnostics.ok) assert.equal(diagnostics.value.invalidated.length, 1); assert.deepEqual(listCapabilityAuditEvents(options).map(event => event.eventType), ['capability.planned', 'validation.requested', 'validation.rejected']) } finally { f.cleanup() }
})
