import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { initializeCapabilityRuntime, scheduleCapabilityRuntimeMaintenance } from '../capability-runtime-bootstrap.js'
import { WORKBENCH_EXECUTION_COORDINATOR_FILENAME } from '../capability-execution-coordinator.js'

test('clean startup initializes deterministically and schedules bounded maintenance', async () => { const rootDir = fs.mkdtempSync(path.join(os.tmpdir(), 'workbench-bootstrap-')); try { const status = initializeCapabilityRuntime({ rootDir, adapters: [] }); assert.equal(status.initialized, true); const scheduled = scheduleCapabilityRuntimeMaintenance({ rootDir, adapters: [], maintenanceDelayMs: 0 }, status); assert.equal(status.maintenance, 'scheduled'); scheduled.cancel(); assert.equal(status.maintenance, 'idle'); const run = scheduled.runNow(); assert.ok(run); assert.equal(status.maintenance, 'completed') } finally { fs.rmSync(rootDir, { recursive: true, force: true }) } })
test('failed recovery is fail-safe and does not throw during startup', () => { const rootDir = fs.mkdtempSync(path.join(os.tmpdir(), 'workbench-bootstrap-')); try { fs.writeFileSync(path.join(rootDir, WORKBENCH_EXECUTION_COORDINATOR_FILENAME), '{invalid'); const status = initializeCapabilityRuntime({ rootDir, adapters: [] }); assert.equal(status.initialized, false); assert.equal(status.maintenance, 'failed') } finally { fs.rmSync(rootDir, { recursive: true, force: true }) } })
test('startup recovery is repeatable after an interrupted execution', () => { const rootDir = fs.mkdtempSync(path.join(os.tmpdir(), 'workbench-bootstrap-')); try { fs.writeFileSync(path.join(rootDir, WORKBENCH_EXECUTION_COORDINATOR_FILENAME), JSON.stringify({ version: 1, updatedAt: '2026-08-23T00:00:00.000Z', records: [{ executionId: 'interrupted', planId: 'plan', lifecycleState: 'running', createdAt: '2026-08-23T00:00:00.000Z', updatedAt: '2026-08-23T00:00:00.000Z', auditReferences: [] }] })); const first = initializeCapabilityRuntime({ rootDir, adapters: [], now: () => new Date('2026-08-23T01:00:00.000Z') }); assert.deepEqual(first.recovered, ['interrupted']); const second = initializeCapabilityRuntime({ rootDir, adapters: [], now: () => new Date('2026-08-23T02:00:00.000Z') }); assert.deepEqual(second.recovered, []) } finally { fs.rmSync(rootDir, { recursive: true, force: true }) } })
