import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { discoverKnowledgeProviders, listKnowledgeProviders, projectKnowledgeProviderContext, registerKnowledgeProvider, removeKnowledgeProvider, transitionKnowledgeProvider, updateKnowledgeProviderHealth, type KnowledgeManifest } from '../knowledge-provider.js'

const manifest = (id = 'docs.provider'): KnowledgeManifest => ({ kind: 'workbench.knowledge.manifest', manifestVersion: 1, providerId: id, providerType: 'documentation', providerVersion: '1.0.0', displayName: 'Documentation', location: { kind: 'opaque-reference', value: `ref:${id}` }, ownership: { ownerType: 'workspace', ownerId: 'workspace-1' }, capabilities: ['search', 'read'], supportedFormats: ['text'], indexing: { full: true, incremental: true, observe: true }, freshness: { strategy: 'revision', revision: 'rev-1', observedAt: new Date().toISOString() }, permissions: ['read'], compatibility: { contractVersion: '1' } })
test('registers, persists, orders, transitions, health-updates, and removes knowledge providers', () => { const rootDir = fs.mkdtempSync(path.join(os.tmpdir(), 'workbench-knowledge-')); try { assert.equal(registerKnowledgeProvider(manifest('zeta'), 'test', { rootDir }).ok, true); assert.equal(registerKnowledgeProvider(manifest('alpha'), 'test', { rootDir }).ok, true); assert.equal(registerKnowledgeProvider(manifest('alpha'), 'test', { rootDir }).ok, false); const listed = listKnowledgeProviders({ rootDir }); assert.equal(listed.ok, true); if (listed.ok) assert.deepEqual(listed.value.map(item => item.providerId), ['alpha', 'zeta']); assert.equal(transitionKnowledgeProvider('alpha', 'enabled', { rootDir }).ok, true); assert.equal(updateKnowledgeProviderHealth('alpha', 'healthy', 'rev-1', { rootDir }).ok, true); const context = projectKnowledgeProviderContext({ rootDir }); assert.ok('healthyProviderIds' in context); if ('healthyProviderIds' in context) assert.deepEqual(context.healthyProviderIds, ['alpha']); assert.equal(removeKnowledgeProvider('zeta', { rootDir }).ok, true) } finally { fs.rmSync(rootDir, { recursive: true, force: true }) } })
test('rejects invalid and duplicate discovery without reading provider content', () => { const first = manifest('same'); const result = discoverKnowledgeProviders([first, first, { kind: 'invalid' }]); assert.equal(result.providers.length, 1); assert.equal(result.failures.length, 2); assert.equal(result.failures[0]?.code, 'duplicate_provider') })
test('disabled and unavailable providers are excluded from readiness', () => { const rootDir = fs.mkdtempSync(path.join(os.tmpdir(), 'workbench-knowledge-')); try { registerKnowledgeProvider(manifest(), 'test', { rootDir }); transitionKnowledgeProvider('docs.provider', 'enabled', { rootDir }); updateKnowledgeProviderHealth('docs.provider', 'unavailable', undefined, { rootDir }); const context = projectKnowledgeProviderContext({ rootDir }); assert.ok('unavailableProviderIds' in context); if ('unavailableProviderIds' in context) assert.deepEqual(context.unavailableProviderIds, ['docs.provider']) } finally { fs.rmSync(rootDir, { recursive: true, force: true }) } })
