import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { KnowledgeIndex } from '../knowledge-index.js'
import { KnowledgeRefreshLifecycle } from '../knowledge-refresh-lifecycle.js'
import type { KnowledgeContentAccess } from '../knowledge-content.js'
import { createRefreshPlan } from '../knowledge-refresh-plan.js'
import { KnowledgeRefreshStore } from '../knowledge-refresh-store.js'

function fixture() { const rootDir = fs.mkdtempSync(path.join(os.tmpdir(), 'workbench-refresh-lifecycle-')); return { rootDir, cleanup: () => fs.rmSync(rootDir, { recursive: true, force: true }) } }
function plan() { return createRefreshPlan(new KnowledgeIndex(), 'docs', { strategy: 'revision', revision: 'r2', observedAt: '2026-01-01T00:00:00.000Z' }, { added: 1, modified: 0, removed: 0, unchanged: 0, bounded: true }, ['a'], 'revision_changed', '2026-01-01T00:00:00.000Z', 'plan-1') }
const provider: KnowledgeContentAccess = { identity: { providerId: 'docs', providerType: 'generic', providerVersion: '1' }, enumerateDocuments: async () => ({ ok: true, value: [] }), getMetadata: async () => ({ ok: false, code: 'not_found', message: 'unused' }), retrieveContent: async () => ({ ok: false, code: 'unavailable', message: 'unused' }), observeFreshness: async () => ({ ok: true, value: { strategy: 'revision', revision: 'r2', observedAt: '2026-01-01T00:00:00.000Z' } }) }

test('persists proposals, requires approval, queues, and completes refresh execution', async () => { const f = fixture(); try { let acceptedJob = ''; const lifecycle = new KnowledgeRefreshLifecycle({ rootDir: f.rootDir, now: () => new Date('2026-01-01T00:00:01.000Z'), queue: { enqueue: async job => { acceptedJob = job.jobId; return { accepted: true } } }, refresh: async () => ({ generation: 2 }) }); const created = lifecycle.create(plan(), '2026-01-01T01:00:00.000Z'); assert.equal(created.ok, true); assert.equal((await lifecycle.enqueue('plan-1')).ok, false); assert.equal(lifecycle.approve('plan-1', '2026-01-01T00:00:02.000Z').ok, true); const queued = await lifecycle.enqueue('plan-1'); assert.equal(queued.ok, true); assert.ok(acceptedJob); if (queued.ok) { const index = new KnowledgeIndex(); const proposal = new KnowledgeRefreshStore({ rootDir: f.rootDir }).get('plan-1'); assert.equal(proposal.ok, true); if (proposal.ok) { const result = await lifecycle.run(queued.value.executionId, proposal.value, provider, index); assert.equal(result.ok, true); if (result.ok) assert.equal(result.value.state, 'completed') } } } finally { f.cleanup() } })
test('reloads proposals and fails closed on corruption', () => { const f = fixture(); try { const store = new KnowledgeRefreshStore({ rootDir: f.rootDir }); assert.equal(store.create(plan(), '2026-01-01T01:00:00.000Z').ok, true); const reloaded = new KnowledgeRefreshStore({ rootDir: f.rootDir }).get('plan-1'); assert.equal(reloaded.ok, true); fs.writeFileSync(path.join(f.rootDir, 'workbench-knowledge-refresh.json'), '{bad'); assert.equal(new KnowledgeRefreshStore({ rootDir: f.rootDir }).get('plan-1').ok, false) } finally { f.cleanup() } })
test('expires approvals, rejects queue failures, and invalidates drifted plans', async () => { const f = fixture(); try { const lifecycle = new KnowledgeRefreshLifecycle({ rootDir: f.rootDir, now: () => new Date('2026-01-02T00:00:00.000Z'), queue: { enqueue: async () => ({ accepted: false as const, reason: 'worker_unavailable' }) }, refresh: async () => ({ generation: 2 }) }); const expired = lifecycle.create(plan(), '2026-01-01T00:00:00.000Z'); assert.equal(expired.ok, true); assert.equal((await lifecycle.enqueue('plan-1')).ok, false); const f2 = fixture(); try { const lifecycle2 = new KnowledgeRefreshLifecycle({ rootDir: f2.rootDir, now: () => new Date('2026-01-01T00:00:01.000Z'), queue: { enqueue: async () => ({ accepted: false as const, reason: 'worker_unavailable' }) }, refresh: async () => ({ generation: 2 }) }); lifecycle2.create(plan(), '2026-01-01T01:00:00.000Z'); lifecycle2.approve('plan-1', '2026-01-01T00:00:02.000Z'); const queued = await lifecycle2.enqueue('plan-1'); assert.deepEqual(queued, { ok: false, code: 'store_busy', message: 'Refresh queue rejected job: worker_unavailable' }) } finally { f2.cleanup() } } finally { f.cleanup() } })
test('invalidates a queued plan when its digest drifts', async () => { const f = fixture(); try { const lifecycle = new KnowledgeRefreshLifecycle({ rootDir: f.rootDir, now: () => new Date('2026-01-01T00:00:01.000Z'), queue: { enqueue: async () => ({ accepted: true as const }) }, refresh: async () => ({ generation: 2 }) }); lifecycle.create(plan(), '2026-01-01T01:00:00.000Z'); lifecycle.approve('plan-1', '2026-01-01T00:00:02.000Z'); const queued = await lifecycle.enqueue('plan-1'); assert.equal(queued.ok, true); if (queued.ok) { const proposal = new KnowledgeRefreshStore({ rootDir: f.rootDir }).get('plan-1'); assert.equal(proposal.ok, true); if (proposal.ok) { proposal.value.planDigest = 'drift'; const result = await lifecycle.run(queued.value.executionId, proposal.value, provider, new KnowledgeIndex()); assert.deepEqual(result, { ok: false, code: 'plan_invalidated', message: 'Refresh plan digest does not match the durable proposal.' }) } } } finally { f.cleanup() } })
