import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { KnowledgeIndexStore } from '../knowledge-index-store.js'
import { KnowledgeContextRuntime, readKnowledgeContextRuntimeStatus } from '../knowledge-context-runtime.js'
import { registerKnowledgeProvider, transitionKnowledgeProvider, updateKnowledgeProviderHealth, type KnowledgeManifest } from '../knowledge-provider.js'
import type { KnowledgeContentAccess } from '../knowledge-content.js'
import { KnowledgeIndex } from '../knowledge-index.js'
import { createKnowledgeDocument } from '../knowledge-document.js'

const manifest: KnowledgeManifest = { kind: 'workbench.knowledge.manifest', manifestVersion: 1, providerId: 'runtime.docs', providerType: 'generic', providerVersion: '1', displayName: 'Runtime docs', location: { kind: 'opaque-reference', value: 'runtime://docs' }, ownership: { ownerType: 'user', ownerId: 'test' }, capabilities: ['content', 'freshness'], supportedFormats: ['generic'], indexing: { full: true, incremental: true, observe: true }, freshness: { strategy: 'revision', revision: 'r1', observedAt: '2026-01-01T00:00:00.000Z' }, permissions: ['read'], compatibility: { contractVersion: '1' } }
function provider(): KnowledgeContentAccess { return { identity: { providerId: 'runtime.docs', providerType: 'generic', providerVersion: '1' }, enumerateDocuments: async () => ({ ok: true, value: [{ documentId: 'guide.md' }] }), getMetadata: async () => ({ ok: true, value: { documentId: 'guide.md', metadata: { path: 'guide.md' } } }), retrieveContent: async () => ({ ok: true, value: { documentId: 'guide.md', content: 'runtime context', contentHash: 'hash', truncated: false } }), observeFreshness: async () => ({ ok: true, value: { strategy: 'revision', revision: 'r1', observedAt: '2026-01-01T00:00:00.000Z' } }) } }
function fixture() { const rootDir = fs.mkdtempSync(path.join(os.tmpdir(), 'workbench-context-runtime-')); return { rootDir, cleanup: () => fs.rmSync(rootDir, { recursive: true, force: true }) } }

test('loads enabled healthy providers and prepares authorized context at runtime', async () => { const f = fixture(); try { registerKnowledgeProvider(manifest, 'test', { rootDir: f.rootDir }); transitionKnowledgeProvider('runtime.docs', 'enabled', { rootDir: f.rootDir }); updateKnowledgeProviderHealth('runtime.docs', 'healthy', 'r1', { rootDir: f.rootDir }); const index = new KnowledgeIndex(); index.register(createKnowledgeDocument({ providerId: 'runtime.docs', documentId: 'guide.md', metadata: { path: 'guide.md', topic: 'runtime' }, permissions: { visibility: 'private', principalIds: [] } }, '2026-01-01T00:00:00.000Z')); index.commitGeneration({ strategy: 'revision', revision: 'r1', observedAt: '2026-01-01T00:00:00.000Z' }, '2026-01-01T00:00:00.000Z'); new KnowledgeIndexStore({ rootDir: f.rootDir }).save('runtime.docs', index, '2026-01-01T00:00:00.000Z'); const runtime = await KnowledgeContextRuntime.initialize({ registry: { rootDir: f.rootDir }, indexRootDir: f.rootDir, providerFactory: async () => provider() }); assert.deepEqual(runtime.status().availableProviders, ['runtime.docs']); assert.equal(runtime.status().providerCount, 1); assert.equal(runtime.status().providers[0]?.indexReady, true); const prepared = await runtime.prepare({ query: 'runtime', sessionId: 'confirmed-session', sourceIds: ['runtime.docs'], limit: 1, maxBytes: 100 }); assert.equal(prepared.ok, true); if (prepared.ok) assert.equal(prepared.package.documents[0]?.document.documentId, 'guide.md'); assert.equal(readKnowledgeContextRuntimeStatus({ registry: { rootDir: f.rootDir } })?.readiness, 'ready') } finally { f.cleanup() } })

test('excludes disabled and unavailable providers without blocking startup', async () => { const f = fixture(); try { registerKnowledgeProvider(manifest, 'test', { rootDir: f.rootDir }); transitionKnowledgeProvider('runtime.docs', 'enabled', { rootDir: f.rootDir }); updateKnowledgeProviderHealth('runtime.docs', 'unavailable', undefined, { rootDir: f.rootDir }); const runtime = await KnowledgeContextRuntime.initialize({ registry: { rootDir: f.rootDir }, providerFactory: async () => undefined }); assert.equal(runtime.status().initialized, true); assert.deepEqual(runtime.status().availableProviders, []); assert.equal(runtime.status().readiness, 'unavailable'); const prepared = await runtime.prepare({ query: 'x', sessionId: 's', sourceIds: ['runtime.docs'], limit: 1, maxBytes: 10 }); assert.equal(prepared.ok, false); if (!prepared.ok) assert.equal(prepared.code, 'source_unavailable') } finally { f.cleanup() } })

test('fails safely when the provider registry is unavailable or corrupt', async () => { const f = fixture(); try { fs.writeFileSync(path.join(f.rootDir, 'workbench-knowledge-providers.json'), '{bad'); const runtime = await KnowledgeContextRuntime.initialize({ registry: { rootDir: f.rootDir } }); assert.equal(runtime.status().initialized, false); const prepared = await runtime.prepare({ query: 'x', sessionId: 's', sourceIds: [], limit: 1, maxBytes: 10 }); assert.equal(prepared.ok, false); if (!prepared.ok) assert.equal(prepared.code, 'knowledge_runtime_unavailable') } finally { f.cleanup() } })
