import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { KnowledgeIndex } from '../knowledge-index.js'
import { KnowledgeRefreshLifecycle } from '../knowledge-refresh-lifecycle.js'
import { KnowledgeRefreshWorker } from '../knowledge-refresh-worker.js'
import { createRefreshPlan } from '../knowledge-refresh-plan.js'
import type { KnowledgeContentAccess } from '../knowledge-content.js'
import { collectKnowledgeRefreshMonitoring } from '../knowledge-refresh-monitor.js'

const provider: KnowledgeContentAccess = { identity: { providerId: 'docs', providerType: 'generic', providerVersion: '1' }, enumerateDocuments: async () => ({ ok: true, value: [] }), getMetadata: async () => ({ ok: false, code: 'not_found', message: 'unused' }), retrieveContent: async () => ({ ok: false, code: 'unavailable', message: 'unused' }), observeFreshness: async () => ({ ok: true, value: { strategy: 'revision', revision: 'r2', observedAt: '2026-01-01T00:00:00.000Z' } }) }
const plan = () => createRefreshPlan(new KnowledgeIndex(), 'docs', { strategy: 'revision', revision: 'r2', observedAt: '2026-01-01T00:00:00.000Z' }, { added: 0, modified: 0, removed: 0, unchanged: 0, bounded: true }, [], 'manual', '2026-01-01T00:00:00.000Z', 'worker-plan')
function fixture() { const rootDir = fs.mkdtempSync(path.join(os.tmpdir(), 'workbench-refresh-worker-')); return { rootDir, cleanup: () => fs.rmSync(rootDir, { recursive: true, force: true }) } }

test('claims and executes approved work once, then reports monitoring metrics', async () => { const f = fixture(); try { const lifecycle = new KnowledgeRefreshLifecycle({ rootDir: f.rootDir, now: () => new Date('2026-01-01T00:00:01.000Z'), queue: { enqueue: async () => ({ accepted: true as const }) }, refresh: async () => ({ generation: 1 }) }); lifecycle.create(plan(), '2026-01-01T01:00:00.000Z'); lifecycle.approve('worker-plan', '2026-01-01T00:00:02.000Z'); const queued = await lifecycle.enqueue('worker-plan'); assert.equal(queued.ok, true); if (queued.ok) { const worker = new KnowledgeRefreshWorker(lifecycle, { provider, index: new KnowledgeIndex(), now: () => new Date('2026-01-01T00:00:03.000Z'), timeoutMs: 1000 }); const result = await worker.run(queued.value.executionId); assert.equal(result.ok, true); const duplicate = await worker.run(queued.value.executionId); assert.equal(duplicate.ok, false); assert.equal(collectKnowledgeRefreshMonitoring(lifecycle.listExecutions()).completedRefreshes, 1) } } finally { f.cleanup() } })

test('supports a bounded retry after provider failure', async () => { const f = fixture(); try { let attempts = 0; const lifecycle = new KnowledgeRefreshLifecycle({ rootDir: f.rootDir, now: () => new Date('2026-01-01T00:00:01.000Z'), queue: { enqueue: async () => ({ accepted: true as const }) }, refresh: async () => { attempts += 1; if (attempts === 1) throw new Error('provider unavailable'); return { generation: 1 } } }); lifecycle.create(plan(), '2026-01-01T01:00:00.000Z'); lifecycle.approve('worker-plan', '2026-01-01T00:00:02.000Z'); const queued = await lifecycle.enqueue('worker-plan'); assert.equal(queued.ok, true); if (queued.ok) { const worker = new KnowledgeRefreshWorker(lifecycle, { provider, index: new KnowledgeIndex(), now: () => new Date('2026-01-01T00:00:03.000Z'), timeoutMs: 1000, maxAttempts: 3 }); const retry = await worker.run(queued.value.executionId); assert.equal(retry.ok, false); assert.match(retry.reason, /retryable/); const completed = await worker.run(queued.value.executionId); assert.equal(completed.ok, true) } } finally { f.cleanup() } })

test('cancels a timed-out worker execution', async () => { const f = fixture(); try { const lifecycle = new KnowledgeRefreshLifecycle({ rootDir: f.rootDir, now: () => new Date('2026-01-01T00:00:01.000Z'), queue: { enqueue: async () => ({ accepted: true as const }) }, refresh: async () => { await new Promise(resolve => setTimeout(resolve, 25)); return { generation: 1 } } }); lifecycle.create(plan(), '2026-01-01T01:00:00.000Z'); lifecycle.approve('worker-plan', '2026-01-01T00:00:02.000Z'); const queued = await lifecycle.enqueue('worker-plan'); assert.equal(queued.ok, true); if (queued.ok) { const worker = new KnowledgeRefreshWorker(lifecycle, { provider, index: new KnowledgeIndex(), now: () => new Date('2026-01-01T00:00:03.000Z'), timeoutMs: 1 }); const result = await worker.run(queued.value.executionId); assert.equal(result.ok, false); assert.equal(lifecycle.listExecutions()[0]?.state, 'cancelled') } } finally { f.cleanup() } })
