import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { KnowledgeIndex } from '../knowledge-index.js'
import { KnowledgeRefreshLifecycle } from '../knowledge-refresh-lifecycle.js'
import { KnowledgeRefreshSupervisor } from '../knowledge-refresh-supervisor.js'
import type { KnowledgeContentAccess } from '../knowledge-content.js'
import { createRefreshPlan } from '../knowledge-refresh-plan.js'

const provider: KnowledgeContentAccess = { identity: { providerId: 'docs', providerType: 'generic', providerVersion: '1' }, enumerateDocuments: async () => ({ ok: true, value: [] }), getMetadata: async () => ({ ok: false, code: 'not_found', message: 'unused' }), retrieveContent: async () => ({ ok: false, code: 'unavailable', message: 'unused' }), observeFreshness: async () => ({ ok: true, value: { strategy: 'revision', revision: 'r2', observedAt: '2026-01-01T00:00:00.000Z' } }) }
function plan() { return createRefreshPlan(new KnowledgeIndex(), 'docs', { strategy: 'revision', revision: 'r2', observedAt: '2026-01-01T00:00:00.000Z' }, { added: 0, modified: 0, removed: 0, unchanged: 0, bounded: true }, [], 'manual', '2026-01-01T00:00:00.000Z', 'supervisor-plan') }
function fixture() { const rootDir = fs.mkdtempSync(path.join(os.tmpdir(), 'workbench-refresh-supervisor-')); return { rootDir, cleanup: () => fs.rmSync(rootDir, { recursive: true, force: true }) } }

test('starts, recovers, runs, and stops one supervisor', async () => { const f = fixture(); try { const lifecycle = new KnowledgeRefreshLifecycle({ rootDir: f.rootDir, now: () => new Date('2026-01-01T00:00:01.000Z'), queue: { enqueue: async () => ({ accepted: true as const }) }, refresh: async () => ({ generation: 1 }) }); lifecycle.create(plan(), '2026-01-01T01:00:00.000Z'); lifecycle.approve('supervisor-plan', '2026-01-01T00:00:02.000Z'); const queued = await lifecycle.enqueue('supervisor-plan'); assert.equal(queued.ok, true); const supervisor = new KnowledgeRefreshSupervisor({ lifecycle, provider, index: new KnowledgeIndex(), supervisorId: 's1', rootIdentity: f.rootDir, now: () => new Date('2026-01-01T00:00:03.000Z') }); assert.equal(supervisor.start().state, 'ready'); if (queued.ok) assert.equal((await supervisor.run(queued.value.executionId)).ok, true); assert.equal(supervisor.stop().state, 'stopped') } finally { f.cleanup() } })

test('prevents duplicate supervisors and supports disabled state', () => { const f = fixture(); try { const make = (id: string) => new KnowledgeRefreshSupervisor({ lifecycle: new KnowledgeRefreshLifecycle({ rootDir: f.rootDir, now: () => new Date(), queue: { enqueue: async () => ({ accepted: true as const }) }, refresh: async () => ({ generation: 1 }) }), provider, index: new KnowledgeIndex(), supervisorId: id, rootIdentity: f.rootDir, now: () => new Date() }); const first = make('first'); const second = make('second'); assert.equal(first.start().state, 'ready'); assert.equal(second.start().state, 'failed'); first.stop(); assert.equal(make('disabled').health().state, 'disabled') } finally { f.cleanup() } })

test('persists ownership, renews leases, and recovers an abandoned owner', () => { const f = fixture(); try { const at = new Date('2026-01-01T00:00:00.000Z'); const make = (id: string, now: Date) => new KnowledgeRefreshSupervisor({ lifecycle: new KnowledgeRefreshLifecycle({ rootDir: f.rootDir, now: () => now, queue: { enqueue: async () => ({ accepted: true as const }) }, refresh: async () => ({ generation: 1 }) }), provider, index: new KnowledgeIndex(), supervisorId: id, rootIdentity: f.rootDir, ownershipLeaseMs: 1000, now: () => now }); const first = make('owner-a', at); assert.equal(first.start().ownershipState, 'acquired'); assert.equal(first.renew().ownershipState, 'renewed'); const conflict = make('owner-b', new Date('2026-01-01T00:00:00.500Z')); assert.equal(conflict.start().state, 'failed'); first.stop(); const recovered = make('owner-b', new Date('2026-01-01T00:00:02.000Z')); assert.equal(recovered.start().state, 'ready'); assert.equal(recovered.health().ownershipState, 'recovered'); recovered.stop() } finally { f.cleanup() } })

test('stale owner cannot continue execution after lease expiry', async () => { const f = fixture(); try { let now = new Date('2026-01-01T00:00:00.000Z'); const lifecycle = new KnowledgeRefreshLifecycle({ rootDir: f.rootDir, now: () => now, queue: { enqueue: async () => ({ accepted: true as const }) }, refresh: async () => ({ generation: 1 }) }); lifecycle.create(plan(), '2026-01-01T01:00:00.000Z'); lifecycle.approve('supervisor-plan', '2026-01-01T00:00:02.000Z'); const queued = await lifecycle.enqueue('supervisor-plan'); assert.equal(queued.ok, true); const supervisor = new KnowledgeRefreshSupervisor({ lifecycle, provider, index: new KnowledgeIndex(), supervisorId: 'expired-owner', rootIdentity: f.rootDir, ownershipLeaseMs: 1000, now: () => now }); assert.equal(supervisor.start().state, 'ready'); now = new Date('2026-01-01T00:00:02.000Z'); if (queued.ok) { const result = await supervisor.run(queued.value.executionId); assert.equal(result.ok, false); assert.equal(result.reason, 'ownership_expired'); assert.equal(supervisor.health().state, 'failed') } } finally { f.cleanup() } })

test('bounded shutdown preserves active execution for restart recovery', async () => { const f = fixture(); try { let release!: () => void; const pending = new Promise<{ generation: number }>(resolve => { release = () => resolve({ generation: 1 }) }); const lifecycle = new KnowledgeRefreshLifecycle({ rootDir: f.rootDir, now: () => new Date('2026-01-01T00:00:01.000Z'), queue: { enqueue: async () => ({ accepted: true as const }) }, refresh: async () => pending }); lifecycle.create(plan(), '2026-01-01T01:00:00.000Z'); lifecycle.approve('supervisor-plan', '2026-01-01T00:00:02.000Z'); const queued = await lifecycle.enqueue('supervisor-plan'); assert.equal(queued.ok, true); const supervisor = new KnowledgeRefreshSupervisor({ lifecycle, provider, index: new KnowledgeIndex(), supervisorId: 'shutdown-owner', rootIdentity: f.rootDir, ownershipLeaseMs: 10_000, timeoutMs: 10_000, now: () => new Date('2026-01-01T00:00:03.000Z') }); assert.equal(supervisor.start().state, 'ready'); if (queued.ok) { const running = supervisor.run(queued.value.executionId); await new Promise(resolve => setImmediate(resolve)); const stopped = await supervisor.shutdown(1); assert.equal(stopped.state, 'stopped'); assert.equal(stopped.lastError, 'shutdown_timeout'); assert.equal(lifecycle.listExecutions()[0]?.state, 'running'); release(); await running } } finally { f.cleanup() } })
