import type { ContextIntelligenceDoctorReport } from './context-intelligence-doctor'

export type DoctorFixtureName = 'healthy' | 'stale-repository' | 'failed-index' | 'active-indexing' | 'expired-context' | 'unavailable-source' | 'queue-recovery'
const health = (overrides: Record<string, unknown> = {}) => ({ schemaVersion: 1, sourceId: 'fixture-source', canonicalRepositoryPath: '/approved/fixture-repository', branchName: 'main', gitStatus: 'clean', trackedChangedFileCount: 0, untrackedFileCount: 0, indexedRevision: 'abc123', observedRevision: 'abc123', indexStatus: 'ready', freshnessState: 'fresh', freshnessScore: 100, runtimeAvailability: 'available', lastCheckedAt: '2026-08-23T12:00:00.000Z', ...overrides })
const job = (overrides: Record<string, unknown> = {}) => ({ schemaVersion: 1, jobId: 'fixture-job', sourceId: 'fixture-source', operation: 'incremental', mode: 'incremental', priority: 'background', status: 'completed', createdAt: '2026-08-23T11:00:00.000Z', updatedAt: '2026-08-23T12:00:00.000Z', completedAt: '2026-08-23T12:00:00.000Z', attempt: 0, maxAttempts: 3, ...overrides })
export function createDoctorFixture(name: DoctorFixtureName): ContextIntelligenceDoctorReport {
  const report: ContextIntelligenceDoctorReport = { schemaVersion: 1, generatedAt: '2026-08-23T12:00:00.000Z', bounded: { maxSources: 64, maxJobs: 500, maxSessions: 200, maxBytes: 32_000 }, context: { mode: 'single', activeSourceIds: ['fixture-source'], confirmedSessions: [{ sessionId: 'fixture-session', clientId: 'fixture-client', status: 'confirmed', sourceIds: ['fixture-source'], authorityLevel: 'confirmed-suggestion', expired: false, confirmationRequired: false }], sessions: [], ambiguousProposals: [], pendingConfirmation: [] }, sources: [{ sourceId: 'fixture-source', label: 'Fixture Source', path: '/approved/fixture-repository', active: true, health: health() as never, jobs: [], remediations: [] }], queue: { queued: [], running: [], stale: [], blocked: [], failed: [], recovered: [], lastSuccessfulIndexing: { 'fixture-source': '2026-08-23T11:00:00.000Z' } }, refreshAudit: { pendingApprovals: [], recentEvents: 0, lastApprovedRefresh: {}, failedRefreshAttempts: [], unresolvedStaleSources: [] }, remediations: [] }
  const source = report.sources[0]
  if (name === 'stale-repository') { source.health = health({ indexedRevision: 'old123', observedRevision: 'abc123', freshnessState: 'stale_revision', freshnessScore: 25 }) as never; source.remediations = [{ code: 'refresh_recommended', message: 'Repository changed since last index; incremental refresh recommended.', automatic: false }]; report.remediations = source.remediations }
  if (name === 'failed-index') { const failed = job({ status: 'failed', error: 'terminal_failure: execution_failed', attempt: 3 }); source.jobs = [{ job: failed as never, ownership: { leaseState: 'none' }, retryHistory: [], failureCodes: ['execution_failed'], recoveryEvents: [], freshnessImpact: 'blocked' }]; report.queue.failed = source.jobs; source.remediations = [{ code: 'manual_intervention_required', message: 'Index failed after retry limit; manual intervention required.', automatic: false }]; report.remediations = source.remediations }
  if (name === 'active-indexing') { const running = job({ jobId: 'running-job', status: 'running', leaseOwner: 'fixture-worker', leaseId: 'lease-1', leaseExpiresAt: '2026-08-23T12:10:00.000Z' }); source.jobs = [{ job: running as never, ownership: { owner: 'fixture-worker', leaseId: 'lease-1', leaseExpiresAt: '2026-08-23T12:10:00.000Z', leaseState: 'active' }, retryHistory: [], failureCodes: [], recoveryEvents: [], freshnessImpact: 'warning' }]; report.queue.running = source.jobs }
  if (name === 'expired-context') { report.context.sessions = [{ sessionId: 'expired-session', clientId: 'fixture-client', status: 'expired', sourceIds: ['fixture-source'], authorityLevel: 'confirmed-suggestion', expired: true, confirmationRequired: false, expiresAt: '2026-08-23T11:00:00.000Z' }]; report.context.confirmedSessions = []; report.context.pendingConfirmation = ['expired-proposal']; report.remediations = [{ code: 'session_expired', message: 'Context session expired; confirmation required.', automatic: false }] }
  if (name === 'unavailable-source') { source.health = health({ runtimeAvailability: 'unavailable', freshnessState: 'unavailable', freshnessScore: 0, gitStatus: 'unavailable' }) as never; source.remediations = [{ code: 'source_unavailable', message: 'Source unavailable; check repository path.', automatic: false }]; report.remediations = source.remediations }
  if (name === 'queue-recovery') { const recovered = job({ status: 'queued', attempt: 1, nextAttemptAt: '2026-08-23T12:01:00.000Z' }); source.jobs = [{ job: recovered as never, ownership: { leaseState: 'none' }, retryHistory: [{ eventId: 'recovery-event', eventType: 'retry_scheduled', jobId: 'fixture-job', sourceId: 'fixture-source', occurredAt: '2026-08-23T12:00:00.000Z', failureCode: 'lease_expired', attempt: 1 }], failureCodes: ['lease_expired'], recoveryEvents: [{ eventId: 'recovery-event-2', eventType: 'recovered', jobId: 'fixture-job', sourceId: 'fixture-source', occurredAt: '2026-08-23T12:00:00.000Z', failureCode: 'lease_expired' }], freshnessImpact: 'warning' }]; report.queue.queued = source.jobs; report.queue.stale = source.jobs; report.queue.recovered = source.jobs }
  return report
}
