import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { getConfigDir } from '../utils/paths'
import { getContextSession, type ContextIntelligenceStoreOptions } from './context-intelligence-store'

export const MCP_SESSION_CAPABILITY_FILENAME = 'mcp-session-capability-grants.json'
export type McpCapabilityApprovalState = 'requested' | 'approved' | 'denied' | 'revoked' | 'expired'
export type McpCapabilityAuthorization = { grantId: string; sessionId: string; capabilityId: string; authorizationSource: 'explicit-user' | 'admin'; approvedBy?: string; approvalState: McpCapabilityApprovalState; grantedAt: string; expiresAt: string; revokedAt?: string; requestId?: string; grantVersion: number; permissions: Array<'read' | 'write' | 'command' | 'git' | 'network' | 'capability'>; budgets: { maximumBytes: number; maximumDurationMs: number; maximumQueries: number } }
export type McpCapabilityStoreOptions = { storePath?: string; now?: () => Date; contextStore?: ContextIntelligenceStoreOptions }
type Store = { version: 1; updatedAt: string; grants: McpCapabilityAuthorization[]; events: Array<{ eventId: string; eventType: 'requested' | 'approved' | 'denied' | 'revoked' | 'expired' | 'allowed' | 'rejected'; occurredAt: string; grantId: string; sessionId: string; capabilityId: string; reason?: string }> }
function file(options: McpCapabilityStoreOptions = {}): string { return path.resolve(options.storePath || path.join(getConfigDir(), MCP_SESSION_CAPABILITY_FILENAME)) }
function read(options: McpCapabilityStoreOptions = {}): Store { try { const value = JSON.parse(fs.readFileSync(file(options), 'utf8')) as Store; if (value.version === 1 && Array.isArray(value.grants) && Array.isArray(value.events)) return value } catch {} return { version: 1, updatedAt: (options.now || (() => new Date()))().toISOString(), grants: [], events: [] } }
function write(store: Store, options: McpCapabilityStoreOptions): void { store.grants = store.grants.slice(-256); store.events = store.events.slice(-512); const target = file(options); fs.mkdirSync(path.dirname(target), { recursive: true, mode: 0o700 }); fs.writeFileSync(target, JSON.stringify(store), { encoding: 'utf8', mode: 0o600 }) }
function event(store: Store, eventType: Store['events'][number]['eventType'], grant: McpCapabilityAuthorization, now: string, reason?: string): void { store.events.push({ eventId: `mcp-capability-${crypto.randomUUID()}`, eventType, occurredAt: now, grantId: grant.grantId, sessionId: grant.sessionId, capabilityId: grant.capabilityId, ...(reason ? { reason } : {}) }) }

export function requestMcpCapability(sessionId: string, capabilityId: string, authorizationSource: McpCapabilityAuthorization['authorizationSource'], expiresAt: string, options: McpCapabilityStoreOptions = {}, binding: { permissions?: McpCapabilityAuthorization['permissions']; budgets?: McpCapabilityAuthorization['budgets'] } = {}): { ok: true; grant: McpCapabilityAuthorization } | { ok: false; code: 'invalid_request' | 'session_missing' | 'session_expired' | 'session_revoked' } {
  const now = (options.now || (() => new Date()))().toISOString(); const session = getContextSession(sessionId, options.contextStore); if (!session || 'ok' in session) return { ok: false, code: 'session_missing' }; if (session.status === 'expired') return { ok: false, code: 'session_expired' }; if (session.status === 'cleared') return { ok: false, code: 'session_revoked' }; if (!capabilityId || !['explicit-user', 'admin'].includes(authorizationSource) || Date.parse(expiresAt) <= Date.parse(now) || (session.expiresAt && Date.parse(expiresAt) > Date.parse(session.expiresAt))) return { ok: false, code: 'invalid_request' }
  const permissions = [...new Set(binding.permissions ?? ['read'])] as McpCapabilityAuthorization['permissions']; const budgets = binding.budgets ?? { maximumBytes: 40_000, maximumDurationMs: 120_000, maximumQueries: 1 }; if (permissions.length === 0 || permissions.length > 6 || Object.values(budgets).some(value => !Number.isFinite(value) || value < 0 || value > 100_000_000)) return { ok: false, code: 'invalid_request' }; const store = read(options); const grant: McpCapabilityAuthorization = { grantId: `mcp-grant-${crypto.randomUUID()}`, sessionId, capabilityId, authorizationSource, approvalState: 'requested', grantedAt: now, expiresAt, grantVersion: 1, permissions, budgets }; store.grants.push(grant); event(store, 'requested', grant, now); store.updatedAt = now; write(store, options); return { ok: true, grant }
}

export function decideMcpCapability(grantId: string, approved: boolean, approvedBy: string | undefined, options: McpCapabilityStoreOptions = {}): { ok: true; grant: McpCapabilityAuthorization } | { ok: false; code: 'grant_missing' | 'authorization_required' | 'invalid_state' } {
  const now = (options.now || (() => new Date()))().toISOString(); const store = read(options); const grant = store.grants.find(item => item.grantId === grantId); if (!grant) return { ok: false, code: 'grant_missing' }; if (approved && !approvedBy) return { ok: false, code: 'authorization_required' }; if (grant.approvalState !== 'requested') return { ok: false, code: 'invalid_state' }; grant.approvalState = approved ? 'approved' : 'denied'; grant.approvedBy = approvedBy; event(store, approved ? 'approved' : 'denied', grant, now, approved ? undefined : 'authorization_denied'); store.updatedAt = now; write(store, options); return { ok: true, grant }
}

export function authorizeMcpCapability(sessionId: string, capabilityId: string, options: McpCapabilityStoreOptions = {}): { ok: true; grant: McpCapabilityAuthorization } | { ok: false; code: 'grant_missing' | 'grant_denied' | 'grant_expired' | 'grant_revoked' | 'session_expired' | 'session_revoked' | 'session_missing' } {
  const now = (options.now || (() => new Date()))().toISOString(); const session = getContextSession(sessionId, options.contextStore); if (!session || 'ok' in session) return { ok: false, code: 'session_missing' }; if (session.status === 'expired') return { ok: false, code: 'session_expired' }; if (session.status === 'cleared') return { ok: false, code: 'session_revoked' }; const store = read(options); const grant = [...store.grants].reverse().find(item => item.sessionId === sessionId && item.capabilityId === capabilityId); if (!grant || grant.approvalState === 'denied' || grant.approvalState === 'requested') return { ok: false, code: 'grant_missing' }; if (grant.approvalState === 'revoked') return { ok: false, code: 'grant_revoked' }; if (grant.approvalState !== 'approved' || Date.parse(grant.expiresAt) <= Date.parse(now)) { if (Date.parse(grant.expiresAt) <= Date.parse(now)) { grant.approvalState = 'expired'; event(store, 'expired', grant, now) } store.updatedAt = now; write(store, options); return { ok: false, code: 'grant_expired' } } if (session.expiresAt && Date.parse(grant.expiresAt) > Date.parse(session.expiresAt)) return { ok: false, code: 'grant_expired' }; event(store, 'allowed', grant, now); store.updatedAt = now; write(store, options); return { ok: true, grant }
}

export function revokeMcpCapability(grantId: string, options: McpCapabilityStoreOptions = {}): { ok: true } | { ok: false; code: 'grant_missing' | 'invalid_state' } { const now = (options.now || (() => new Date()))().toISOString(); const store = read(options); const grant = store.grants.find(item => item.grantId === grantId); if (!grant) return { ok: false, code: 'grant_missing' }; if (grant.approvalState === 'revoked') return { ok: false, code: 'invalid_state' }; grant.approvalState = 'revoked'; grant.revokedAt = now; event(store, 'revoked', grant, now); store.updatedAt = now; write(store, options); return { ok: true } }

export function getMcpCapabilityDiagnostics(options: McpCapabilityStoreOptions = {}): { grants: { requested: number; approved: number; denied: number; expired: number; revoked: number; orphaned: number; exceedingSessionLifetime: number }; recentEvents: Store['events'] } { const store = read(options); const now = (options.now || (() => new Date()))().getTime(); let orphaned = 0; let exceeding = 0; for (const grant of store.grants) { const session = getContextSession(grant.sessionId, options.contextStore); if (!session || 'ok' in session) orphaned += 1; if (session && !('ok' in session) && session.expiresAt && Date.parse(grant.expiresAt) > Date.parse(session.expiresAt)) exceeding += 1; if (Date.parse(grant.expiresAt) <= now && grant.approvalState === 'approved') grant.approvalState = 'expired' } return { grants: { requested: store.grants.filter(item => item.approvalState === 'requested').length, approved: store.grants.filter(item => item.approvalState === 'approved').length, denied: store.grants.filter(item => item.approvalState === 'denied').length, expired: store.grants.filter(item => item.approvalState === 'expired').length, revoked: store.grants.filter(item => item.approvalState === 'revoked').length, orphaned, exceedingSessionLifetime: exceeding }, recentEvents: store.events.slice(-32) } }
