import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'

export const CAPABILITY_AUDIT_FILENAME = 'workbench-capability-audit.json' as const
export type CapabilityAuditEventType = 'capability.planned' | 'validation.requested' | 'validation.approved' | 'validation.rejected' | 'execution.requested' | 'execution.completed' | 'execution.failed'
export type CapabilityAuditEvent = { eventId: string; eventType: CapabilityAuditEventType; planId?: string; validationId?: string; executionId?: string; providerId?: string; capabilityId?: string; occurredAt: string; reason?: string }
export type CapabilityAuditOptions = { rootDir?: string; maxEvents?: number }
const MAX_EVENTS = 1000
function file(options: CapabilityAuditOptions = {}): string { return path.join(path.resolve(options.rootDir ?? path.join(process.cwd(), '.workbench-provider-state')), CAPABILITY_AUDIT_FILENAME) }
function bounded(value: unknown, max: number): value is string { return typeof value === 'string' && value.length > 0 && value.length <= max }
function valid(value: unknown): value is CapabilityAuditEvent { if (!value || typeof value !== 'object' || Array.isArray(value)) return false; const item = value as Record<string, unknown>; return bounded(item.eventId, 200) && ['capability.planned', 'validation.requested', 'validation.approved', 'validation.rejected', 'execution.requested', 'execution.completed', 'execution.failed'].includes(String(item.eventType)) && typeof item.occurredAt === 'string' && Number.isFinite(Date.parse(item.occurredAt)) }
export function recordCapabilityAuditEvent(event: Omit<CapabilityAuditEvent, 'eventId'>, options: CapabilityAuditOptions = {}): void { try { const target = file(options); fs.mkdirSync(path.dirname(target), { recursive: true, mode: 0o700 }); let events: CapabilityAuditEvent[] = []; if (fs.existsSync(target)) { let parsed: { version?: unknown; events?: unknown[] }; try { parsed = JSON.parse(fs.readFileSync(target, 'utf8')) as { version?: unknown; events?: unknown[] } } catch { return } if (parsed.version !== 1 || !Array.isArray(parsed.events) || !parsed.events.every(valid)) return; events = parsed.events } events.push({ ...event, eventId: `capability-audit-${crypto.randomUUID()}` }); const max = Math.min(Math.max(1, options.maxEvents ?? MAX_EVENTS), MAX_EVENTS); fs.writeFileSync(target, JSON.stringify({ version: 1, updatedAt: event.occurredAt, events: events.slice(-max) }), { encoding: 'utf8', mode: 0o600 }); fs.chmodSync(target, 0o600) } catch {} }
export function listCapabilityAuditEvents(options: CapabilityAuditOptions = {}): CapabilityAuditEvent[] { try { const parsed = JSON.parse(fs.readFileSync(file(options), 'utf8')) as { events?: unknown[] }; return Array.isArray(parsed.events) ? parsed.events.filter(valid).slice(-Math.min(Math.max(1, options.maxEvents ?? MAX_EVENTS), MAX_EVENTS)) : [] } catch { return [] } }
export function capabilityAuditDiagnostics(options?: CapabilityAuditOptions): { planned: string[]; validationPending: string[]; validationApproved: string[]; validationRejected: string[]; executionPending: string[]; executionCompleted: string[]; executionFailed: string[] } { const events = listCapabilityAuditEvents(options); const terminalValidation = new Set(events.filter(item => ['validation.approved', 'validation.rejected'].includes(item.eventType)).map(item => item.validationId).filter(Boolean)); const terminalExecution = new Set(events.filter(item => ['execution.completed', 'execution.failed'].includes(item.eventType)).map(item => item.executionId).filter(Boolean)); return { planned: events.filter(item => item.eventType === 'capability.planned').map(item => item.planId!).slice(-64), validationPending: events.filter(item => item.eventType === 'validation.requested' && !terminalValidation.has(item.validationId)).map(item => item.validationId!).slice(-64), validationApproved: events.filter(item => item.eventType === 'validation.approved').map(item => item.validationId!).slice(-64), validationRejected: events.filter(item => item.eventType === 'validation.rejected').map(item => item.validationId!).slice(-64), executionPending: events.filter(item => item.eventType === 'execution.requested' && !terminalExecution.has(item.executionId)).map(item => item.executionId!).slice(-64), executionCompleted: events.filter(item => item.eventType === 'execution.completed').map(item => item.executionId!).slice(-64), executionFailed: events.filter(item => item.eventType === 'execution.failed').map(item => item.executionId!).slice(-64) } }
