import type { KnowledgeContentAccess } from './knowledge-content.js'
import type { KnowledgeIndex } from './knowledge-index.js'
import { KnowledgeRefreshEngine } from './knowledge-refresh.js'
import { knowledgeRefreshPlanDigest, KnowledgeRefreshStore, type KnowledgeRefreshExecutionRecord, type KnowledgeRefreshProposal, type KnowledgeRefreshStoreOptions, type KnowledgeRefreshStoreResult } from './knowledge-refresh-store.js'
import type { KnowledgeRefreshPlan } from './knowledge-refresh-plan.js'
import type { KnowledgeRefreshQueue, KnowledgeRefreshJob } from './knowledge-refresh-approval.js'

export type KnowledgeRefreshExecutionState = KnowledgeRefreshExecutionRecord['state']
export type KnowledgeRefreshExecution = KnowledgeRefreshExecutionRecord
export type KnowledgeRefreshLifecycleOptions = KnowledgeRefreshStoreOptions & { now: () => Date; queue: KnowledgeRefreshQueue; refresh: (provider: KnowledgeContentAccess) => Promise<{ generation: number }> }

export class KnowledgeRefreshLifecycle {
  private readonly store: KnowledgeRefreshStore
  private readonly executions = new Map<string, KnowledgeRefreshExecution>()
  constructor(private readonly options: KnowledgeRefreshLifecycleOptions) { this.store = new KnowledgeRefreshStore(options); const existing = this.store.listExecutions(); if (existing.ok) for (const execution of existing.value) this.executions.set(execution.executionId, execution) }
  rootDir(): string { return this.options.rootDir }
  create(plan: KnowledgeRefreshPlan, expiresAt: string): KnowledgeRefreshStoreResult<KnowledgeRefreshProposal> { return this.store.create(plan, expiresAt) }
  approve(proposalId: string, at: string): KnowledgeRefreshStoreResult<KnowledgeRefreshProposal> { return this.store.transition(proposalId, 'approved', at) }
  reject(proposalId: string, at: string, reason: string): KnowledgeRefreshStoreResult<KnowledgeRefreshProposal> { return this.store.transition(proposalId, 'rejected', at, reason) }
  invalidate(proposalId: string, at: string, reason: string): KnowledgeRefreshStoreResult<KnowledgeRefreshProposal> { return this.store.transition(proposalId, 'invalidated', at, reason) }
  async enqueue(proposalId: string): Promise<KnowledgeRefreshStoreResult<KnowledgeRefreshExecution>> { const proposal = this.store.get(proposalId); if (!proposal.ok) return proposal; if (proposal.value.approvalState !== 'approved') return { ok: false, code: 'invalid_transition', message: 'Refresh proposal is not approved.' }; if (Date.parse(this.options.now().toISOString()) >= Date.parse(proposal.value.expiresAt)) { this.store.transition(proposalId, 'expired', this.options.now().toISOString(), 'approval_expired'); return { ok: false, code: 'proposal_expired', message: 'Refresh proposal has expired.' }; } const executionId = `knowledge-refresh-execution-${proposalId}`; const existing = this.executions.get(executionId); if (existing && ['queued', 'running', 'completed'].includes(existing.state)) return { ok: false, code: 'invalid_transition', message: 'Refresh execution already exists.' }; const execution: KnowledgeRefreshExecution = existing ? { ...existing, state: 'queued', updatedAt: this.options.now().toISOString(), error: undefined } : { executionId, proposalId, providerId: proposal.value.providerId, state: 'queued', attempts: 0, createdAt: this.options.now().toISOString(), updatedAt: this.options.now().toISOString() }; const queued = await this.options.queue.enqueue({ jobId: execution.executionId, planId: proposalId, providerId: proposal.value.providerId, queuedAt: execution.updatedAt, reason: proposal.value.reason }); if (!queued.accepted) return { ok: false, code: 'store_busy', message: `Refresh queue rejected job: ${queued.reason}` }; this.executions.set(execution.executionId, execution); const saved = this.store.saveExecution(execution, execution.updatedAt); return saved.ok ? saved : saved }
  async run(executionId: string, proposal: KnowledgeRefreshProposal, provider: KnowledgeContentAccess, index: KnowledgeIndex): Promise<KnowledgeRefreshStoreResult<KnowledgeRefreshExecution>> { const execution = this.executions.get(executionId); if (!execution) return { ok: false, code: 'proposal_missing', message: 'Refresh execution was not found.' }; const now = () => this.options.now().toISOString(); if (proposal.approvalState !== 'approved') return { ok: false, code: 'invalid_transition', message: 'Refresh execution requires approval.' }; if (proposal.planDigest !== knowledgeRefreshPlanDigest(proposal)) return { ok: false, code: 'plan_invalidated', message: 'Refresh plan digest does not match the durable proposal.' }; if (proposal.providerId !== provider.identity.providerId) return { ok: false, code: 'plan_invalidated', message: 'Provider identity changed.' }; const expectedGeneration = Number(proposal.indexIdentity.split(':').at(-1)); if (index.status(provider.identity.providerId).generation !== expectedGeneration) return { ok: false, code: 'plan_invalidated', message: 'Index generation changed since planning.' }; if (execution.state !== 'running') { execution.state = 'running'; execution.attempts += 1; execution.updatedAt = now(); this.store.saveExecution(execution, execution.updatedAt) } try { const result = await this.options.refresh(provider); const cancelled = this.executions.get(executionId)?.state === 'cancelled'; if (!cancelled) { execution.state = 'completed'; execution.resultingGeneration = result.generation; execution.completedAt = now(); execution.updatedAt = execution.completedAt } } catch (error) { const cancelled = this.executions.get(executionId)?.state === 'cancelled'; if (!cancelled) { execution.state = 'failed'; execution.error = error instanceof Error ? error.message : 'Refresh failed.'; execution.updatedAt = now() } } const saved = this.store.saveExecution(execution, execution.updatedAt); return saved.ok ? saved : saved }
  async runApproved(executionId: string, provider: KnowledgeContentAccess, index: KnowledgeIndex): Promise<KnowledgeRefreshStoreResult<KnowledgeRefreshExecution>> { const proposal = this.store.get(this.executions.get(executionId)?.proposalId ?? ''); if (!proposal.ok) return proposal; return this.run(executionId, proposal.value, provider, index) }
  listExecutions(): KnowledgeRefreshExecution[] { return [...this.executions.values()].map(item => ({ ...item })) }
  claim(executionId: string, leaseMs: number): KnowledgeRefreshStoreResult<KnowledgeRefreshExecution> { const execution = this.executions.get(executionId); if (!execution) return { ok: false, code: 'proposal_missing', message: 'Refresh execution was not found.' }; const now = this.options.now(); if (execution.state !== 'queued') return { ok: false, code: 'invalid_transition', message: 'Refresh execution is not queued.' }; execution.state = 'running'; execution.attempts += 1; execution.startedAt = now.toISOString(); execution.updatedAt = now.toISOString(); execution.leaseExpiresAt = new Date(now.getTime() + Math.max(1, leaseMs)).toISOString(); const saved = this.store.saveExecution(execution, execution.updatedAt); return saved.ok ? saved : saved }
  cancel(executionId: string, reason = 'cancelled'): KnowledgeRefreshStoreResult<KnowledgeRefreshExecution> { const execution = this.executions.get(executionId); if (!execution) return { ok: false, code: 'proposal_missing', message: 'Refresh execution was not found.' }; if (['completed', 'failed', 'cancelled', 'expired'].includes(execution.state)) return { ok: false, code: 'invalid_transition', message: 'Refresh execution is terminal.' }; execution.state = 'cancelled'; execution.error = reason; execution.updatedAt = this.options.now().toISOString(); const saved = this.store.saveExecution(execution, execution.updatedAt); return saved.ok ? saved : saved }
  recover(now = this.options.now()): KnowledgeRefreshExecution[] { const recovered: KnowledgeRefreshExecution[] = []; for (const execution of this.executions.values()) if (execution.state === 'running' && execution.leaseExpiresAt && Date.parse(execution.leaseExpiresAt) <= now.getTime()) { execution.state = 'failed'; execution.error = 'worker_lease_expired'; execution.updatedAt = now.toISOString(); this.store.saveExecution(execution, execution.updatedAt); recovered.push({ ...execution }) } return recovered }
  retry(executionId: string): KnowledgeRefreshStoreResult<KnowledgeRefreshExecution> { const execution = this.executions.get(executionId); if (!execution || execution.state !== 'failed') return { ok: false, code: 'invalid_transition', message: 'Only failed refresh executions can retry.' }; execution.state = 'queued'; execution.updatedAt = this.options.now().toISOString(); const saved = this.store.saveExecution(execution, execution.updatedAt); return saved.ok ? saved : saved }
}
