import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import type { KnowledgeRefreshPlan } from './knowledge-refresh-plan.js'

export const KNOWLEDGE_REFRESH_STORE_VERSION = 1 as const
export const KNOWLEDGE_REFRESH_STORE_FILENAME = 'workbench-knowledge-refresh.json' as const
export type KnowledgeRefreshProposal = KnowledgeRefreshPlan & { planDigest: string; expiresAt: string; auditReferences: string[] }
export type KnowledgeRefreshStoreEvent = { eventId: string; eventType: 'proposal.created' | 'proposal.approved' | 'proposal.rejected' | 'proposal.expired' | 'proposal.invalidated' | 'refresh.queued' | 'refresh.started' | 'refresh.completed' | 'refresh.failed' | 'refresh.cancelled'; proposalId: string; occurredAt: string; reason?: string }
export type KnowledgeRefreshExecutionRecord = { executionId: string; proposalId: string; providerId: string; state: 'proposed' | 'approved' | 'queued' | 'running' | 'completed' | 'failed' | 'cancelled' | 'expired'; attempts: number; createdAt: string; updatedAt: string; startedAt?: string; completedAt?: string; leaseExpiresAt?: string; providerHealth?: string; error?: string; resultingGeneration?: number }
export type KnowledgeRefreshStoreResult<T> = { ok: true; value: T } | { ok: false; code: 'store_corrupt' | 'store_busy' | 'proposal_missing' | 'proposal_exists' | 'invalid_transition' | 'proposal_expired' | 'plan_invalidated'; message: string }
type State = { version: typeof KNOWLEDGE_REFRESH_STORE_VERSION; updatedAt: string; proposals: KnowledgeRefreshProposal[]; events: KnowledgeRefreshStoreEvent[]; executions: KnowledgeRefreshExecutionRecord[] }
export type KnowledgeRefreshStoreOptions = { rootDir: string; maxProposals?: number; maxEvents?: number }

function digest(plan: KnowledgeRefreshPlan): string { const canonical = { planId: plan.planId, providerId: plan.providerId, indexIdentity: plan.indexIdentity, currentRevision: plan.currentRevision, observedRevision: plan.observedRevision, changeEstimate: plan.changeEstimate, affectedDocuments: [...plan.affectedDocuments].sort(), reason: plan.reason, freshnessImpact: plan.freshnessImpact, observedAt: plan.observedAt }; return crypto.createHash('sha256').update(JSON.stringify(canonical)).digest('hex') }
function file(options: KnowledgeRefreshStoreOptions): string { return path.join(path.resolve(options.rootDir), KNOWLEDGE_REFRESH_STORE_FILENAME) }
function event(type: KnowledgeRefreshStoreEvent['eventType'], proposalId: string, at: string, reason?: string): KnowledgeRefreshStoreEvent { return { eventId: `knowledge-refresh-event-${crypto.randomUUID()}`, eventType: type, proposalId, occurredAt: at, ...(reason ? { reason } : {}) } }

export class KnowledgeRefreshStore {
  constructor(private readonly options: KnowledgeRefreshStoreOptions) {}
  private read(): KnowledgeRefreshStoreResult<State> { try { const target = file(this.options); if (!fs.existsSync(target)) return { ok: true, value: { version: 1, updatedAt: new Date(0).toISOString(), proposals: [], events: [], executions: [] } }; const value = JSON.parse(fs.readFileSync(target, 'utf8')) as State; if (value.version !== 1 || !Array.isArray(value.proposals) || !Array.isArray(value.events) || !Array.isArray(value.executions) || value.proposals.length > (this.options.maxProposals ?? 500) || value.events.length > (this.options.maxEvents ?? 1_000)) return { ok: false, code: 'store_corrupt', message: 'Knowledge refresh store shape is invalid.' }; return { ok: true, value } } catch { return { ok: false, code: 'store_corrupt', message: 'Knowledge refresh store could not be read safely.' } }
  }
  private write(state: State): KnowledgeRefreshStoreResult<boolean> { const target = file(this.options); const lock = `${target}.lock`; let fd: number | undefined; try { fs.mkdirSync(path.dirname(target), { recursive: true, mode: 0o700 }); try { fd = fs.openSync(lock, 'wx', 0o600) } catch { return { ok: false, code: 'store_busy', message: 'Knowledge refresh store is busy.' } }; const temp = `${target}.${process.pid}.${crypto.randomBytes(8).toString('hex')}.tmp`; const normalized = { version: 1 as const, updatedAt: state.updatedAt, proposals: [...state.proposals].sort((a, b) => a.planId.localeCompare(b.planId)).slice(-(this.options.maxProposals ?? 500)), events: state.events.slice(-(this.options.maxEvents ?? 1_000)), executions: [...state.executions].sort((a, b) => a.executionId.localeCompare(b.executionId)).slice(-(this.options.maxProposals ?? 500)) }; fs.writeFileSync(temp, JSON.stringify(normalized), { encoding: 'utf8', mode: 0o600, flag: 'wx' }); fs.renameSync(temp, target); fs.chmodSync(target, 0o600); return { ok: true, value: true } } catch { return { ok: false, code: 'store_corrupt', message: 'Knowledge refresh store persistence failed safely.' } } finally { if (fd !== undefined) { try { fs.closeSync(fd) } catch {} ; try { fs.rmSync(lock, { force: true }) } catch {} } } }
  private mutate<T>(fn: (state: State) => KnowledgeRefreshStoreResult<T>, at: string): KnowledgeRefreshStoreResult<T> { const current = this.read(); if (!current.ok) return current; const result = fn(current.value); if (result.ok) { current.value.updatedAt = at; const saved = this.write(current.value); if (!saved.ok) return saved } return result }
  create(plan: KnowledgeRefreshPlan, expiresAt: string): KnowledgeRefreshStoreResult<KnowledgeRefreshProposal> { const value = { ...plan, planDigest: digest(plan), expiresAt, auditReferences: [] }; return this.mutate(state => { if (state.proposals.some(item => item.planId === plan.planId)) return { ok: false, code: 'proposal_exists', message: 'Refresh proposal already exists.' }; state.proposals.push(value); state.events.push(event('proposal.created', plan.planId, plan.observedAt)); return { ok: true, value } }, plan.observedAt) }
  get(planId: string): KnowledgeRefreshStoreResult<KnowledgeRefreshProposal> { const state = this.read(); if (!state.ok) return state; const proposal = state.value.proposals.find(item => item.planId === planId); return proposal ? { ok: true, value: { ...proposal, affectedDocuments: [...proposal.affectedDocuments], auditReferences: [...proposal.auditReferences] } } : { ok: false, code: 'proposal_missing', message: 'Refresh proposal was not found.' } }
  transition(planId: string, target: 'approved' | 'rejected' | 'expired' | 'invalidated', at: string, reason?: string): KnowledgeRefreshStoreResult<KnowledgeRefreshProposal> { return this.mutate(state => { const proposal = state.proposals.find(item => item.planId === planId); if (!proposal) return { ok: false, code: 'proposal_missing', message: 'Refresh proposal was not found.' }; if (proposal.approvalState !== 'pending' && target !== 'expired') return { ok: false, code: 'invalid_transition', message: 'Refresh proposal is no longer pending.' }; if (target === 'approved' && Date.parse(at) >= Date.parse(proposal.expiresAt)) { proposal.approvalState = 'expired'; state.events.push(event('proposal.expired', planId, at, 'approval_expired')); return { ok: false, code: 'proposal_expired', message: 'Refresh proposal has expired.' } } proposal.approvalState = target; const type = target === 'approved' ? 'proposal.approved' : target === 'rejected' ? 'proposal.rejected' : target === 'expired' ? 'proposal.expired' : 'proposal.invalidated'; state.events.push(event(type, planId, at, reason)); return { ok: true, value: proposal } }, at) }
  list(): KnowledgeRefreshStoreResult<KnowledgeRefreshProposal[]> { const state = this.read(); return state.ok ? { ok: true, value: state.value.proposals.map(item => ({ ...item, affectedDocuments: [...item.affectedDocuments], auditReferences: [...item.auditReferences] })) } : state }
  events(): KnowledgeRefreshStoreResult<KnowledgeRefreshStoreEvent[]> { const state = this.read(); return state.ok ? { ok: true, value: [...state.value.events] } : state }
  saveExecution(execution: KnowledgeRefreshExecutionRecord, at: string): KnowledgeRefreshStoreResult<KnowledgeRefreshExecutionRecord> { return this.mutate(state => { const index = state.executions.findIndex(item => item.executionId === execution.executionId); if (index >= 0) state.executions[index] = { ...execution }; else state.executions.push({ ...execution }); return { ok: true, value: { ...execution } } }, at) }
  listExecutions(): KnowledgeRefreshStoreResult<KnowledgeRefreshExecutionRecord[]> { const state = this.read(); return state.ok ? { ok: true, value: state.value.executions.map(item => ({ ...item })) } : state }
}

export function knowledgeRefreshPlanDigest(plan: KnowledgeRefreshPlan): string { return digest(plan) }
