import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'

export const KNOWLEDGE_MANIFEST_KIND = 'workbench.knowledge.manifest' as const
export const KNOWLEDGE_MANIFEST_VERSION = 1 as const
export const KNOWLEDGE_REGISTRY_VERSION = 1 as const
export const KNOWLEDGE_REGISTRY_FILENAME = 'workbench-knowledge-providers.json' as const
export type KnowledgeProviderType = string
export type KnowledgeHealth = 'unknown' | 'healthy' | 'stale' | 'degraded' | 'unavailable'
export type KnowledgeLifecycle = 'discovered' | 'registered' | 'enabled' | 'disabled'
export type KnowledgeManifest = { kind: typeof KNOWLEDGE_MANIFEST_KIND; manifestVersion: typeof KNOWLEDGE_MANIFEST_VERSION; providerId: string; providerType: KnowledgeProviderType; providerVersion: string; displayName: string; location: { kind: 'local-path' | 'url' | 'opaque-reference'; value: string }; ownership: { ownerType: 'user' | 'workspace' | 'organization'; ownerId: string }; capabilities: string[]; supportedFormats: string[]; indexing: { full: boolean; incremental: boolean; observe: boolean }; freshness: { strategy: 'revision' | 'timestamp' | 'external' | 'unknown'; revision?: string; observedAt: string }; permissions: string[]; compatibility: { contractVersion: string; workbenchMinVersion?: string; workbenchMaxVersion?: string } }
export type KnowledgeProvider = KnowledgeManifest & { health: KnowledgeHealth; lifecycle: KnowledgeLifecycle; indexedRevision?: string; lastCheckedAt: string; auditIdentity: { registeredAt: string; registeredBy: string } }
export type KnowledgeRegistryOptions = { rootDir?: string; maxProviders?: number; now?: () => Date }
export type KnowledgeResult<T> = { ok: true; value: T } | { ok: false; code: 'registry_busy' | 'registry_corrupt' | 'invalid_manifest' | 'duplicate_provider' | 'provider_missing' | 'invalid_transition' | 'registry_limit'; message: string }
export type KnowledgeDiscovery = { providers: KnowledgeProvider[]; failures: Array<{ location: string; code: string; message: string }>; observedAt: string }

const ID = /^[a-z][a-z0-9._-]{0,159}$/; const ISO = (value: unknown): value is string => typeof value === 'string' && Number.isFinite(Date.parse(value)) && new Date(value).toISOString() === value
const bounded = (value: unknown, max: number): value is string => typeof value === 'string' && value.length > 0 && value.length <= max
const record = (value: unknown): value is Record<string, unknown> => !!value && typeof value === 'object' && !Array.isArray(value)
function validManifest(value: unknown): value is KnowledgeManifest { if (!record(value) || value.kind !== KNOWLEDGE_MANIFEST_KIND || value.manifestVersion !== KNOWLEDGE_MANIFEST_VERSION || !ID.test(String(value.providerId ?? '')) || !bounded(value.providerType, 64) || !bounded(value.providerVersion, 64) || !bounded(value.displayName, 256)) return false; const location = value.location as Record<string, unknown>; const ownership = value.ownership as Record<string, unknown>; const freshness = value.freshness as Record<string, unknown>; const compatibility = value.compatibility as Record<string, unknown>; const indexing = value.indexing as Record<string, unknown>; return record(location) && ['local-path', 'url', 'opaque-reference'].includes(String(location.kind)) && bounded(location.value, 2048) && record(ownership) && ['user', 'workspace', 'organization'].includes(String(ownership.ownerType)) && bounded(ownership.ownerId, 160) && Array.isArray(value.capabilities) && value.capabilities.length <= 128 && value.capabilities.every(item => bounded(item, 160)) && Array.isArray(value.supportedFormats) && value.supportedFormats.length <= 128 && value.supportedFormats.every(item => bounded(item, 80)) && record(indexing) && typeof indexing.full === 'boolean' && typeof indexing.incremental === 'boolean' && typeof indexing.observe === 'boolean' && record(freshness) && ['revision', 'timestamp', 'external', 'unknown'].includes(String(freshness.strategy)) && ISO(freshness.observedAt) && (freshness.revision === undefined || bounded(freshness.revision, 256)) && Array.isArray(value.permissions) && value.permissions.length <= 32 && value.permissions.every(item => bounded(item, 80)) && record(compatibility) && bounded(compatibility.contractVersion, 32) && (compatibility.workbenchMinVersion === undefined || bounded(compatibility.workbenchMinVersion, 32)) && (compatibility.workbenchMaxVersion === undefined || bounded(compatibility.workbenchMaxVersion, 32)) }
export function validateKnowledgeManifest(value: unknown): value is KnowledgeManifest { return validManifest(value) }
export function parseKnowledgeManifest(value: unknown): KnowledgeManifest { if (!validManifest(value)) throw new Error('invalid knowledge provider manifest'); return value }
function root(options?: KnowledgeRegistryOptions): string { return path.resolve(options?.rootDir ?? path.join(process.cwd(), '.workbench-provider-state')) }
export function getKnowledgeRegistryPath(options?: KnowledgeRegistryOptions): string { return path.join(root(options), KNOWLEDGE_REGISTRY_FILENAME) }
function now(options?: KnowledgeRegistryOptions): string { return (options?.now ?? (() => new Date()))().toISOString() }
function empty(): { version: 1; updatedAt: string; providers: KnowledgeProvider[] } { return { version: 1, updatedAt: new Date(0).toISOString(), providers: [] } }
function read(options?: KnowledgeRegistryOptions): KnowledgeResult<{ version: 1; updatedAt: string; providers: KnowledgeProvider[] }> { try { const target = getKnowledgeRegistryPath(options); if (!fs.existsSync(target)) return { ok: true, value: empty() }; const value = JSON.parse(fs.readFileSync(target, 'utf8')) as { version?: number; updatedAt?: unknown; providers?: unknown[] }; if (value.version !== 1 || !ISO(value.updatedAt) || !Array.isArray(value.providers) || !value.providers.every((item: unknown) => record(item) && validManifest(item) && ['unknown', 'healthy', 'stale', 'degraded', 'unavailable'].includes(String((item as KnowledgeProvider).health)) && ['discovered', 'registered', 'enabled', 'disabled'].includes(String((item as KnowledgeProvider).lifecycle)) && ISO((item as KnowledgeProvider).lastCheckedAt) && record((item as KnowledgeProvider).auditIdentity))) return { ok: false, code: 'registry_corrupt', message: 'Knowledge provider registry is invalid.' }; return { ok: true, value: { version: 1, updatedAt: value.updatedAt as string, providers: value.providers as KnowledgeProvider[] } } } catch { return { ok: false, code: 'registry_corrupt', message: 'Knowledge provider registry could not be read.' } } }
function persist(value: { version: 1; updatedAt: string; providers: KnowledgeProvider[] }, options?: KnowledgeRegistryOptions): void { const target = getKnowledgeRegistryPath(options); fs.mkdirSync(path.dirname(target), { recursive: true, mode: 0o700 }); const temp = `${target}.${process.pid}.${crypto.randomBytes(8).toString('hex')}.tmp`; fs.writeFileSync(temp, JSON.stringify({ ...value, providers: [...value.providers].sort((a, b) => a.providerId.localeCompare(b.providerId)) }), { encoding: 'utf8', mode: 0o600, flag: 'wx' }); fs.renameSync(temp, target); fs.chmodSync(target, 0o600) }
function withLock<T>(options: KnowledgeRegistryOptions | undefined, fn: (value: { version: 1; updatedAt: string; providers: KnowledgeProvider[] }, timestamp: string) => KnowledgeResult<T>): KnowledgeResult<T> { const lock = `${getKnowledgeRegistryPath(options)}.lock`; let fd: number | undefined; try { fs.mkdirSync(path.dirname(lock), { recursive: true, mode: 0o700 }); try { fd = fs.openSync(lock, 'wx', 0o600) } catch { return { ok: false, code: 'registry_busy', message: 'Knowledge provider registry is busy.' } }; const current = read(options); if (!current.ok) return current; const result = fn(current.value, now(options)); if (result.ok) { current.value.updatedAt = now(options); persist(current.value, options) }; return result } catch { return { ok: false, code: 'registry_corrupt', message: 'Knowledge provider registry operation failed.' } } finally { if (fd !== undefined) { try { fs.closeSync(fd) } catch {} ; try { fs.rmSync(lock, { force: true }) } catch {} } } }

export function registerKnowledgeProvider(manifest: KnowledgeManifest, registeredBy: string, options?: KnowledgeRegistryOptions): KnowledgeResult<KnowledgeProvider> { if (!validManifest(manifest) || !bounded(registeredBy, 160)) return { ok: false, code: 'invalid_manifest', message: 'Knowledge provider manifest or audit identity is invalid.' }; return withLock(options, (store, timestamp) => { if (store.providers.some(item => item.providerId === manifest.providerId)) return { ok: false, code: 'duplicate_provider', message: `Knowledge provider ${manifest.providerId} already exists.` }; if (store.providers.length >= Math.min(options?.maxProviders ?? 500, 500)) return { ok: false, code: 'registry_limit', message: 'Knowledge provider registry limit reached.' }; const provider: KnowledgeProvider = { ...manifest, health: 'unknown', lifecycle: 'registered', lastCheckedAt: timestamp, auditIdentity: { registeredAt: timestamp, registeredBy } }; store.providers.push(provider); return { ok: true, value: provider } }) }
export function listKnowledgeProviders(options?: KnowledgeRegistryOptions): KnowledgeResult<KnowledgeProvider[]> { const result = read(options); return result.ok ? { ok: true, value: [...result.value.providers].sort((a, b) => a.providerId.localeCompare(b.providerId)) } : result }
export function transitionKnowledgeProvider(providerId: string, lifecycle: KnowledgeLifecycle, options?: KnowledgeRegistryOptions): KnowledgeResult<KnowledgeProvider> { return withLock(options, (store, timestamp) => { const provider = store.providers.find(item => item.providerId === providerId); if (!provider) return { ok: false, code: 'provider_missing', message: 'Knowledge provider was not found.' }; const allowed: Record<KnowledgeLifecycle, KnowledgeLifecycle[]> = { discovered: ['registered'], registered: ['enabled', 'disabled'], enabled: ['disabled'], disabled: ['enabled'] }; if (!allowed[provider.lifecycle].includes(lifecycle)) return { ok: false, code: 'invalid_transition', message: 'Knowledge provider lifecycle transition is invalid.' }; provider.lifecycle = lifecycle; provider.lastCheckedAt = timestamp; return { ok: true, value: provider } }) }
export function updateKnowledgeProviderHealth(providerId: string, health: KnowledgeHealth, indexedRevision?: string, options?: KnowledgeRegistryOptions): KnowledgeResult<KnowledgeProvider> { return withLock(options, (store, timestamp) => { const provider = store.providers.find(item => item.providerId === providerId); if (!provider) return { ok: false, code: 'provider_missing', message: 'Knowledge provider was not found.' }; provider.health = health; provider.indexedRevision = indexedRevision; provider.lastCheckedAt = timestamp; return { ok: true, value: provider } }) }
export function removeKnowledgeProvider(providerId: string, options?: KnowledgeRegistryOptions): KnowledgeResult<boolean> { return withLock(options, (store) => { const before = store.providers.length; store.providers = store.providers.filter(item => item.providerId !== providerId); return before === store.providers.length ? { ok: false, code: 'provider_missing', message: 'Knowledge provider was not found.' } : { ok: true, value: true } }) }
export function discoverKnowledgeProviders(manifests: readonly unknown[], options?: KnowledgeRegistryOptions): KnowledgeDiscovery { const observedAt = now(options); const providers: KnowledgeProvider[] = []; const failures: KnowledgeDiscovery['failures'] = []; const seen = new Set<string>(); for (const value of manifests.slice(0, 64)) { try { const manifest = parseKnowledgeManifest(value); if (seen.has(manifest.providerId)) { failures.push({ location: manifest.location.value, code: 'duplicate_provider', message: 'Duplicate provider identity.' }); continue } seen.add(manifest.providerId); providers.push({ ...manifest, health: 'unknown', lifecycle: 'discovered', lastCheckedAt: observedAt, auditIdentity: { registeredAt: observedAt, registeredBy: 'discovery' } }) } catch { failures.push({ location: 'unknown', code: 'invalid_manifest', message: 'Knowledge manifest failed validation.' }) } } return { providers: providers.sort((a, b) => a.providerId.localeCompare(b.providerId)), failures, observedAt } }
export function projectKnowledgeProviderContext(options?: KnowledgeRegistryOptions): { availableProviderIds: string[]; unavailableProviderIds: string[]; healthyProviderIds: string[]; freshness: Record<string, { indexedRevision?: string; observedRevision?: string; strategy: string; ready: boolean }> } | { code: string; message: string } { const result = listKnowledgeProviders(options); if (!result.ok) return result; const available = result.value.filter(item => item.lifecycle !== 'disabled' && item.health !== 'unavailable'); return { availableProviderIds: available.map(item => item.providerId), unavailableProviderIds: result.value.filter(item => item.health === 'unavailable' || item.lifecycle === 'disabled').map(item => item.providerId), healthyProviderIds: available.filter(item => item.health === 'healthy').map(item => item.providerId), freshness: Object.fromEntries(result.value.map(item => [item.providerId, { indexedRevision: item.indexedRevision, observedRevision: item.freshness.revision, strategy: item.freshness.strategy, ready: item.lifecycle === 'enabled' && item.health === 'healthy' && item.indexing.observe }])) } }
