import crypto from 'node:crypto'
import type { KnowledgeRefreshPlan } from './knowledge-refresh-plan.js'

export type KnowledgeRefreshAuditEvent = { eventId: string; eventType: 'proposal.created' | 'proposal.approved' | 'proposal.rejected' | 'refresh.scheduled' | 'refresh.failed'; planId: string; providerId: string; occurredAt: string; reason?: string }
export type KnowledgeRefreshApprovalStore = { plans: Map<string, KnowledgeRefreshPlan>; events: KnowledgeRefreshAuditEvent[]; maxEvents: number }
export type KnowledgeRefreshJob = { jobId: string; planId: string; providerId: string; queuedAt: string; reason: string }
export type KnowledgeRefreshQueue = { enqueue(job: KnowledgeRefreshJob): Promise<{ accepted: true } | { accepted: false; reason: string }> }

export function createKnowledgeRefreshApprovalStore(maxEvents = 500): KnowledgeRefreshApprovalStore { return { plans: new Map(), events: [], maxEvents } }
function audit(store: KnowledgeRefreshApprovalStore, event: Omit<KnowledgeRefreshAuditEvent, 'eventId'>): void { store.events.push({ eventId: `knowledge-refresh-${crypto.randomUUID()}`, ...event }); if (store.events.length > store.maxEvents) store.events.splice(0, store.events.length - store.maxEvents) }

export function createRefreshProposal(store: KnowledgeRefreshApprovalStore, plan: KnowledgeRefreshPlan): { ok: true; plan: KnowledgeRefreshPlan } | { ok: false; reason: string } {
  if (store.plans.has(plan.planId)) return { ok: false, reason: 'proposal_exists' }
  store.plans.set(plan.planId, { ...plan, affectedDocuments: [...plan.affectedDocuments] }); audit(store, { eventType: 'proposal.created', planId: plan.planId, providerId: plan.providerId, occurredAt: plan.observedAt, reason: plan.reason }); return { ok: true, plan }
}
export function approveRefreshProposal(store: KnowledgeRefreshApprovalStore, planId: string, approvedAt: string): { ok: true; plan: KnowledgeRefreshPlan } | { ok: false; reason: string } { const plan = store.plans.get(planId); if (!plan) return { ok: false, reason: 'proposal_missing' }; if (plan.approvalState !== 'pending') return { ok: false, reason: `proposal_not_pending:${plan.approvalState}` }; const next = { ...plan, approvalState: 'approved' as const }; store.plans.set(planId, next); audit(store, { eventType: 'proposal.approved', planId, providerId: plan.providerId, occurredAt: approvedAt }); return { ok: true, plan: next } }
export function rejectRefreshProposal(store: KnowledgeRefreshApprovalStore, planId: string, rejectedAt: string, reason: string): { ok: true } | { ok: false; reason: string } { const plan = store.plans.get(planId); if (!plan) return { ok: false, reason: 'proposal_missing' }; if (plan.approvalState !== 'pending') return { ok: false, reason: `proposal_not_pending:${plan.approvalState}` }; store.plans.set(planId, { ...plan, approvalState: 'rejected' }); audit(store, { eventType: 'proposal.rejected', planId, providerId: plan.providerId, occurredAt: rejectedAt, reason }); return { ok: true } }
export async function scheduleApprovedRefresh(store: KnowledgeRefreshApprovalStore, queue: KnowledgeRefreshQueue, planId: string, queuedAt: string): Promise<{ ok: true; job: KnowledgeRefreshJob } | { ok: false; reason: string }> { const plan = store.plans.get(planId); if (!plan) return { ok: false, reason: 'proposal_missing' }; if (plan.approvalState !== 'approved') return { ok: false, reason: 'approval_required' }; const job = { jobId: `knowledge-refresh-job-${crypto.randomUUID()}`, planId, providerId: plan.providerId, queuedAt, reason: plan.reason }; const accepted = await queue.enqueue(job); if (!accepted.accepted) { audit(store, { eventType: 'refresh.failed', planId, providerId: plan.providerId, occurredAt: queuedAt, reason: accepted.reason }); return { ok: false, reason: `queue_rejected:${accepted.reason}` }; } audit(store, { eventType: 'refresh.scheduled', planId, providerId: plan.providerId, occurredAt: queuedAt }); return { ok: true, job } }
