import { FilesystemKnowledgeProvider } from './filesystem-knowledge-provider.js'
import { KnowledgeIndex } from './knowledge-index.js'
import { KnowledgeIndexStore } from './knowledge-index-store.js'
import type { KnowledgeContentAccess } from './knowledge-content.js'
import { listKnowledgeProviders, type KnowledgeProvider, type KnowledgeRegistryOptions } from './knowledge-provider.js'
import { IndexedKnowledgeRetrieval, type KnowledgeContextBudget, type KnowledgeContextPackage, type KnowledgeContextAuthorization, type KnowledgeRetrievalDiagnostics, type KnowledgeRetrievalQuery } from './knowledge-retrieval.js'
import fs from 'node:fs'
import path from 'node:path'

export const KNOWLEDGE_CONTEXT_RUNTIME_STATUS_FILENAME = 'workbench-knowledge-context-runtime.json' as const
export type KnowledgeContextProviderStatus = { providerId: string; registryHealth: string; available: boolean; indexReady: boolean; retrievalCapable?: boolean; indexGeneration: number; freshness?: { strategy: string; revision?: string; observedAt: string }; failure?: string }
export type KnowledgeContextRuntimeStatus = { initialized: boolean; readiness: 'ready' | 'warning' | 'unavailable'; enabledProviders: string[]; availableProviders: string[]; providerCount: number; providers: KnowledgeContextProviderStatus[]; retrievalReady: boolean; lastInitializedAt: string; lastSuccessfulRetrievalAt?: string; retrievalFailures: number; warnings: string[]; failedProviders: Array<{ providerId: string; reason: string }> }
export type KnowledgeContextRuntimeOptions = { registry?: KnowledgeRegistryOptions; indexRootDir?: string; now?: () => Date; budget?: KnowledgeContextBudget; providerFactory?: (provider: KnowledgeProvider) => Promise<KnowledgeContentAccess | undefined>; activeProviderIds?: readonly string[] }
export type KnowledgeContextPreparationInput = { query: string; sessionId: string; sourceIds: string[]; limit: number; maxBytes: number }
export type KnowledgeContextPreparationResult = { ok: true; package: KnowledgeContextPackage; diagnostics: KnowledgeRetrievalDiagnostics } | { ok: false; code: string; message: string; diagnostics?: KnowledgeRetrievalDiagnostics }

const DEFAULT_BUDGET: KnowledgeContextBudget = { maximumRepositories: 1, maximumFiles: 5, maximumBytes: 40_000, maximumTokens: 10_000, maximumQueries: 1 }

export class KnowledgeContextRuntime {
  private readonly retrieval: IndexedKnowledgeRetrieval
  private readonly statusValue: KnowledgeContextRuntimeStatus
  private constructor(private readonly options: KnowledgeContextRuntimeOptions, status: KnowledgeContextRuntimeStatus, retrieval: IndexedKnowledgeRetrieval) { this.statusValue = status; this.retrieval = retrieval }
  static async initialize(options: KnowledgeContextRuntimeOptions = {}): Promise<KnowledgeContextRuntime> {
    const now = (options.now ?? (() => new Date()))().toISOString(); const registry = listKnowledgeProviders(options.registry); const active = options.activeProviderIds ? new Set(options.activeProviderIds) : undefined; const enabled = registry.ok ? registry.value.filter(provider => provider.lifecycle === 'enabled' && (!active || active.has(provider.providerId))) : []; const failed: KnowledgeContextRuntimeStatus['failedProviders'] = []; const providerStatuses: KnowledgeContextProviderStatus[] = []; const providers = new Map<string, KnowledgeContentAccess>(); const index = new KnowledgeIndex()
    if (!registry.ok) { const status = { initialized: false, readiness: 'unavailable' as const, enabledProviders: [], availableProviders: [], providerCount: 0, providers: [], retrievalReady: false, failedProviders: [{ providerId: '*', reason: registry.message }], lastInitializedAt: now, retrievalFailures: 0, warnings: ['Knowledge provider registry is unavailable.'] }; persistKnowledgeContextRuntimeStatus(status, options); return new KnowledgeContextRuntime(options, status, new IndexedKnowledgeRetrieval(index, providers)) }
    for (const provider of enabled.slice(0, 64)) {
      try {
        if (provider.health === 'unavailable') { failed.push({ providerId: provider.providerId, reason: 'registry_health_unavailable' }); providerStatuses.push({ providerId: provider.providerId, registryHealth: provider.health, available: false, indexReady: false, retrievalCapable: false, indexGeneration: 0, failure: 'registry_health_unavailable' }); continue }
        const access = await (options.providerFactory?.(provider) ?? KnowledgeContextRuntime.defaultFactory(provider)); if (!access) { failed.push({ providerId: provider.providerId, reason: 'provider_type_unsupported' }); providerStatuses.push({ providerId: provider.providerId, registryHealth: provider.health, available: false, indexReady: false, retrievalCapable: false, indexGeneration: 0, failure: 'provider_type_unsupported' }); continue }
        const freshness = await access.observeFreshness(); if (!freshness.ok) { failed.push({ providerId: provider.providerId, reason: `provider_unavailable:${freshness.code}` }); providerStatuses.push({ providerId: provider.providerId, registryHealth: provider.health, available: false, indexReady: false, retrievalCapable: false, indexGeneration: 0, failure: `provider_unavailable:${freshness.code}` }); continue }
        const loaded = new KnowledgeIndexStore({ rootDir: options.indexRootDir ?? options.registry?.rootDir ?? process.cwd() }).load(provider.providerId); let indexGeneration = 0; let indexReady = false; if (loaded.ok) { for (const document of loaded.value.list(provider.providerId)) index.register(document); const loadedStatus = loaded.value.status(provider.providerId); indexGeneration = loadedStatus.generation; indexReady = indexGeneration > 0; if (indexReady) index.commitGeneration(loadedStatus.freshness, loadedStatus.refreshTimestamp ?? now) }
        providers.set(provider.providerId, access)
        providerStatuses.push({ providerId: provider.providerId, registryHealth: provider.health, available: true, indexReady, retrievalCapable: true, indexGeneration, freshness: { strategy: freshness.value.strategy, ...(freshness.value.revision ? { revision: freshness.value.revision } : {}), observedAt: freshness.value.observedAt } })
      } catch (error) { const reason = error instanceof Error ? error.message : 'provider_initialization_failed'; failed.push({ providerId: provider.providerId, reason }); providerStatuses.push({ providerId: provider.providerId, registryHealth: provider.health, available: false, indexReady: false, retrievalCapable: false, indexGeneration: 0, failure: reason }) }
    }
    const warnings = failed.map(item => `${item.providerId}: ${item.reason}`).slice(0, 16); const readiness = failed.length > 0 ? (providers.size > 0 ? 'warning' as const : 'unavailable' as const) : (providers.size > 0 ? 'ready' as const : 'unavailable' as const); const status = { initialized: true, readiness, enabledProviders: enabled.map(provider => provider.providerId).sort(), availableProviders: [...providers.keys()].sort(), providerCount: enabled.length, providers: providerStatuses.sort((a, b) => a.providerId.localeCompare(b.providerId)).slice(0, 64), retrievalReady: providers.size > 0, failedProviders: failed.slice(0, 32), lastInitializedAt: now, retrievalFailures: 0, warnings: warnings.length ? warnings : (enabled.length === 0 ? ['No enabled knowledge providers are available.'] : []) }; persistKnowledgeContextRuntimeStatus(status, options); return new KnowledgeContextRuntime(options, status, new IndexedKnowledgeRetrieval(index, providers))
  }
  private static async defaultFactory(provider: KnowledgeProvider): Promise<KnowledgeContentAccess | undefined> { if (provider.providerType !== 'filesystem' || provider.location.kind !== 'local-path') return undefined; const access = new FilesystemKnowledgeProvider({ rootPath: provider.location.value, providerId: provider.providerId, providerVersion: provider.providerVersion }); const health = await access.connect(); return health.ok && health.value.available ? access : undefined }
  status(): KnowledgeContextRuntimeStatus { return { ...this.statusValue, enabledProviders: [...this.statusValue.enabledProviders], availableProviders: [...this.statusValue.availableProviders], providers: this.statusValue.providers.map(item => ({ ...item })), failedProviders: this.statusValue.failedProviders.map(item => ({ ...item })), warnings: [...this.statusValue.warnings] } }
  async prepare(input: KnowledgeContextPreparationInput): Promise<KnowledgeContextPreparationResult> {
    if (!this.statusValue.initialized) { this.statusValue.retrievalFailures += 1; return { ok: false, code: 'knowledge_runtime_unavailable', message: 'Knowledge context runtime is unavailable.' } }
    const unavailable = input.sourceIds.filter(sourceId => this.statusValue.enabledProviders.includes(sourceId) && !this.statusValue.availableProviders.includes(sourceId))
    if (unavailable.length > 0) { this.statusValue.retrievalFailures += 1; return { ok: false, code: 'source_unavailable', message: `Knowledge source(s) unavailable: ${unavailable.join(', ')}` } }
    const authorization: KnowledgeContextAuthorization = { sessionId: input.sessionId, sessionStatus: 'confirmed', sourceIds: input.sourceIds }
    const query: KnowledgeRetrievalQuery = { keywords: input.query, limit: input.limit }
    const result = await this.retrieval.packageContext(query, authorization, { ...(this.options.budget ?? DEFAULT_BUDGET), maximumFiles: Math.min(input.limit, this.options.budget?.maximumFiles ?? DEFAULT_BUDGET.maximumFiles), maximumBytes: Math.min(input.maxBytes, this.options.budget?.maximumBytes ?? DEFAULT_BUDGET.maximumBytes) })
    if (result.ok) { this.statusValue.lastSuccessfulRetrievalAt = (this.options.now ?? (() => new Date()))().toISOString(); persistKnowledgeContextRuntimeStatus(this.statusValue, this.options); return { ok: true, package: result.package, diagnostics: result.diagnostics } }
    this.statusValue.retrievalFailures += 1; persistKnowledgeContextRuntimeStatus(this.statusValue, this.options); return result
  }
}

function statusPath(options: KnowledgeContextRuntimeOptions): string { return path.join(path.resolve(options.registry?.rootDir ?? process.cwd()), KNOWLEDGE_CONTEXT_RUNTIME_STATUS_FILENAME) }
export function persistKnowledgeContextRuntimeStatus(status: KnowledgeContextRuntimeStatus, options: KnowledgeContextRuntimeOptions = {}): void { try { const target = statusPath(options); fs.mkdirSync(path.dirname(target), { recursive: true, mode: 0o700 }); fs.writeFileSync(target, JSON.stringify({ version: 1, ...status, providers: status.providers.slice(0, 64), enabledProviders: status.enabledProviders.slice(0, 64), availableProviders: status.availableProviders.slice(0, 64), failedProviders: status.failedProviders.slice(0, 32), warnings: status.warnings.slice(0, 16) }), { encoding: 'utf8', mode: 0o600 }) } catch {} }
export function readKnowledgeContextRuntimeStatus(options: KnowledgeContextRuntimeOptions = {}): KnowledgeContextRuntimeStatus | undefined { try { const value = JSON.parse(fs.readFileSync(statusPath(options), 'utf8')) as { version?: number } & KnowledgeContextRuntimeStatus; return value.version === 1 && typeof value.initialized === 'boolean' ? value : undefined } catch { return undefined } }

export async function initializeKnowledgeContextRuntime(options: KnowledgeContextRuntimeOptions = {}): Promise<KnowledgeContextRuntime> { return KnowledgeContextRuntime.initialize(options) }
