import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import type { CapabilityAdapter, CapabilityAdapterHealth, CapabilityAdapterValidation, DispatchRequest, DispatchDecision } from './capability-dispatch.js'
import type { CapabilityPlan } from './capability-planning.js'
import type { ExecutionValidationResult } from './capability-pre-execution.js'
import type { ProviderInventoryRecord } from './provider-inventory.js'
import { createWorkbenchClient, type BridgeResult } from './client.js'
import type { WorkbenchToolContract } from './contracts.js'
import { recordMcpExecutionProvenance } from './mcp-execution-provenance.js'
import { recordCapabilityAuditEvent } from './capability-audit.js'

export const WORKBENCH_MCP_EXECUTION_AUDIT_FILENAME = 'workbench-mcp-execution-audit.json' as const
export type McpExecutionRequest = DispatchRequest & { dispatchId: string; operation: string; signal?: AbortSignal }
export type McpExecutionEvidence = { check: string; passed: boolean; detail: string }
export type McpExecutionResult = { executionId: string; status: 'completed' | 'failed' | 'cancelled'; output?: unknown; metadata: { providerId: string; capabilityId: string; operation: string; durationMs: number }; errors: Array<{ code: string; message: string }>; evidence: McpExecutionEvidence[]; auditReferences: { executionId: string; dispatchId: string; validationId: string }; dispatchId: string; validationId: string; code?: string }
export type McpExecutionBoundary = (request: McpExecutionRequest) => Promise<BridgeResult>
export type McpExecutionAuthorization = { decision: DispatchDecision; plan?: CapabilityPlan; validation?: ExecutionValidationResult; provider?: ProviderInventoryRecord }
export type McpExecutionOptions = { rootDir?: string; now?: () => Date; boundary?: McpExecutionBoundary; contract?: WorkbenchToolContract; timeoutMs?: number }
export type McpExecutionAuditEvent = { eventId: string; eventType: 'execution_requested' | 'authorization_verified' | 'execution_admitted' | 'execution_started' | 'execution_completed' | 'execution_failed' | 'execution_denied' | 'execution_cancelled'; executionId: string; dispatchId: string; planId: string; validationId: string; occurredAt: string; providerId: string; capabilityId: string; code?: string }

function auditPath(options: McpExecutionOptions): string { return path.join(path.resolve(options.rootDir ?? path.join(process.cwd(), '.workbench-provider-state')), WORKBENCH_MCP_EXECUTION_AUDIT_FILENAME) }
function writeAudit(events: McpExecutionAuditEvent[], options: McpExecutionOptions): void { const file = auditPath(options); fs.mkdirSync(path.dirname(file), { recursive: true, mode: 0o700 }); fs.writeFileSync(file, JSON.stringify({ version: 1, updatedAt: events.at(-1)?.occurredAt ?? new Date(0).toISOString(), events: events.slice(-500) }), { encoding: 'utf8', mode: 0o600 }) }
export function listMcpExecutionAudit(options: McpExecutionOptions = {}): McpExecutionAuditEvent[] { try { const value = JSON.parse(fs.readFileSync(auditPath(options), 'utf8')) as { events?: McpExecutionAuditEvent[] }; return Array.isArray(value.events) ? value.events : [] } catch { return [] } }
export function mcpExecutionDiagnostics(options: McpExecutionOptions = {}): { pending: string[]; admitted: string[]; completed: string[]; failed: string[]; denied: string[]; cancelled: string[]; recentErrors: string[]; metrics: { admitted: number; rejected: number; averageLatencyMs: number; capabilityUsage: Record<string, number>; failureCategories: Record<string, number> } } {
  const events = listMcpExecutionAudit(options); const terminal = new Map<string, McpExecutionAuditEvent>()
  for (const event of events) if (['execution_completed', 'execution_failed', 'execution_denied', 'execution_cancelled'].includes(event.eventType)) terminal.set(event.executionId, event)
  const requested = new Map(events.filter(event => event.eventType === 'execution_requested').map(event => [event.executionId, event])); const capabilityUsage: Record<string, number> = {}; const failureCategories: Record<string, number> = {}; let latencyTotal = 0; let latencyCount = 0; for (const event of terminal.values()) { if (event.eventType === 'execution_completed' || event.eventType === 'execution_failed') { const start = requested.get(event.executionId); if (start) { latencyTotal += Math.max(0, Date.parse(event.occurredAt) - Date.parse(start.occurredAt)); latencyCount += 1 } } capabilityUsage[event.capabilityId] = (capabilityUsage[event.capabilityId] || 0) + 1; if (event.code) failureCategories[event.code] = (failureCategories[event.code] || 0) + 1 }
  return { pending: events.filter(event => event.eventType === 'execution_requested').map(event => event.executionId).filter(id => !terminal.has(id)), admitted: events.filter(event => event.eventType === 'execution_admitted').map(event => event.executionId), completed: [...terminal.values()].filter(event => event.eventType === 'execution_completed').map(event => event.executionId), failed: [...terminal.values()].filter(event => event.eventType === 'execution_failed').map(event => event.executionId), denied: [...terminal.values()].filter(event => event.eventType === 'execution_denied').map(event => event.executionId), cancelled: [...terminal.values()].filter(event => event.eventType === 'execution_cancelled').map(event => event.executionId), recentErrors: [...terminal.values()].filter(event => ['execution_failed', 'execution_denied'].includes(event.eventType) && !!event.code).map(event => event.code!).slice(-20), metrics: { admitted: events.filter(event => event.eventType === 'execution_admitted').length, rejected: [...terminal.values()].filter(event => event.eventType === 'execution_denied').length, averageLatencyMs: latencyCount ? Math.round(latencyTotal / latencyCount) : 0, capabilityUsage, failureCategories } }
}

export class McpCapabilityAdapter implements CapabilityAdapter {
  readonly adapterId = 'mcp-capability-adapter-v1'
  readonly supportedProviderTypes: ProviderInventoryRecord['providerType'][] = ['capability']
  readonly capabilityTypes = ['*']
  constructor(private readonly options: McpExecutionOptions = {}) {}
  healthCheck(): CapabilityAdapterHealth { return { available: !!this.options.boundary || !!this.options.contract, detail: this.options.boundary || this.options.contract ? 'Authenticated Workbench MCP boundary is available.' : 'An admitted MCP tool contract is required.' } }
  validate(request: DispatchRequest): CapabilityAdapterValidation { return request.requestedOperation.length > 0 ? { valid: true, detail: 'MCP capability request is bounded and identified.' } : { valid: false, detail: 'MCP capability operation is required.' } }
  dispatch(): { executed: false; reason: 'execution_not_implemented' } { return { executed: false, reason: 'execution_not_implemented' } }

  async executeApproved(request: McpExecutionRequest, authorization: McpExecutionAuthorization): Promise<McpExecutionResult> {
    const now = this.options.now ?? (() => new Date()); const started = now(); const executionId = `mcp-execution-${crypto.randomUUID()}`; const evidence: McpExecutionEvidence[] = []; const events = listMcpExecutionAudit(this.options)
    const plan = authorization.plan; const grantId = plan?.grantBinding?.grantId || plan?.auditIdentity?.grantId || ''
    const provenanceId = `mcp-provenance-${crypto.randomUUID()}`
    const provenance = (lifecycle: 'requested'|'admitted'|'completed'|'failed'|'denied'|'cancelled', outcome?: 'completed'|'failed'|'denied'|'cancelled', failureCode?: string) => recordMcpExecutionProvenance({ provenanceId, sessionId: request.contextSessionId, requestId: request.auditIdentity.requestedBy, executionId, dispatchId: request.dispatchId, capabilityId: request.capabilityId, authorizationGrantId: grantId, authorizationApprovedAt: plan?.auditIdentity?.createdAt || '', authorizationApprovedBy: plan?.auditIdentity?.createdBy || '', authorizationValidAtExecution: Boolean(grantId && plan && plan.approvalState === 'approved' && plan.validity === 'valid'), providerId: request.providerId, sourceIds: plan?.sourceIds || [], contextOrigin: request.contextSessionId, planId: request.capabilityPlanId, validationId: request.validationId, occurredAt: now().toISOString(), lifecycle, ...(outcome ? { outcome } : {}), ...(failureCode ? { failureCode } : {}), evidence: evidence.map((item, index) => ({ evidenceId: `evidence-${index + 1}`, kind: item.check, reference: item.detail, recordedAt: now().toISOString() })) }, this.options)
    provenance('requested')
    const base = { executionId, dispatchId: request.dispatchId, providerId: request.providerId, capabilityId: request.capabilityId, operation: request.operation, validationId: request.validationId }
    events.push({ eventId: crypto.randomUUID(), eventType: 'execution_requested', planId: request.capabilityPlanId, occurredAt: started.toISOString(), ...base }); recordCapabilityAuditEvent({ eventType: 'execution.requested', executionId, planId: request.capabilityPlanId, providerId: request.providerId, capabilityId: request.capabilityId, occurredAt: started.toISOString() }, this.options)
    const add = (check: string, passed: boolean, detail: string) => evidence.push({ check, passed, detail })
    const replayed = events.some(event => event.dispatchId === request.dispatchId && ['execution_started', 'execution_completed', 'execution_failed', 'execution_denied', 'execution_cancelled'].includes(event.eventType)); add('replay_check', !replayed, replayed ? 'Dispatch identity has already reached an execution terminal or started state.' : 'Dispatch identity has not been executed previously.')
    const validDispatch = !replayed && authorization.decision.status === 'accepted' && authorization.decision.dispatchId === request.dispatchId && authorization.decision.adapterId === this.adapterId; add('dispatch_accepted', validDispatch, validDispatch ? 'Dispatch was accepted by the selected MCP adapter.' : 'Execution requires the selected adapter and an accepted dispatch.')
    const validation = authorization.validation; const validValidation = !!validation && validation.allowed && validation.outcome === 'allowed' && validation.validationId === request.validationId && Date.parse(started.toISOString()) < Date.parse(validation.expiresAt); add('validation', validValidation, validValidation ? 'Pre-execution validation is allowed and current.' : 'Validation is missing, denied, invalidated, expired, or mismatched.')
    const validPlan = !!plan && plan.planId === request.capabilityPlanId && plan.approvalState === 'approved' && plan.validity === 'valid' && plan.contextSessionId === request.contextSessionId && plan.providerId === request.providerId && plan.capabilityId === request.capabilityId && plan.requestedOperation === request.requestedOperation && Date.parse(started.toISOString()) < Date.parse(plan.expiresAt); add('capability_plan', validPlan, validPlan ? 'Approved capability plan matches the execution request.' : 'Capability plan is missing, expired, unapproved, invalid, or mismatched.')
    const provider = authorization.provider; const activeProvider = !!provider && provider.providerId === request.providerId && provider.enabled && provider.registrationState === 'enabled' && provider.health === 'healthy' && provider.capabilities.includes(request.capabilityId); add('provider_active', activeProvider, activeProvider ? 'Provider is enabled, healthy, and advertises the capability.' : 'Provider is missing, changed, disabled, unhealthy, or capability is unavailable.')
    if (request.signal?.aborted) { provenance('cancelled','cancelled','cancelled'); return this.finish({ ...base, status: 'cancelled', metadata: this.metadata(base, started, now()), errors: [{ code: 'cancelled', message: 'Execution was cancelled before the MCP boundary call.' }], evidence }, events, this.options) }
    if (!validDispatch || !validValidation || !validPlan || !activeProvider) { const code = replayed ? 'execution_replay' : !validValidation ? 'validation_required' : !validPlan ? 'invalid_plan' : !activeProvider ? 'provider_unavailable' : 'dispatch_not_accepted'; provenance('denied','denied',code); return this.finish({ ...base, status: 'failed', metadata: this.metadata(base, started, now()), errors: [{ code, message: 'MCP execution failed closed before contacting the MCP boundary.' }], evidence }, events, this.options, true) }
    provenance('admitted')
    events.push({ eventId: crypto.randomUUID(), eventType: 'authorization_verified', planId: request.capabilityPlanId, occurredAt: now().toISOString(), ...base }); events.push({ eventId: crypto.randomUUID(), eventType: 'execution_admitted', planId: request.capabilityPlanId, occurredAt: now().toISOString(), ...base }); writeAudit(events, this.options)
    events.push({ eventId: crypto.randomUUID(), eventType: 'execution_started', planId: request.capabilityPlanId, occurredAt: now().toISOString(), ...base }); writeAudit(events, this.options)
    const boundary = this.options.boundary ?? (this.options.contract ? async (value: McpExecutionRequest) => createWorkbenchClient()(this.options.contract!, { ...value }, value.signal) : undefined)
    if (!boundary) { provenance('failed','failed','boundary_unavailable'); return this.finish({ ...base, status: 'failed', metadata: this.metadata(base, started, now()), errors: [{ code: 'boundary_unavailable', message: 'An admitted MCP tool contract is required.' }], evidence }, events, this.options) }
    const timeoutMs = Math.max(1, Math.min(this.options.timeoutMs ?? 120_000, 300_000)); let timeoutHandle: ReturnType<typeof setTimeout> | undefined; let timedOut = false
    let result: BridgeResult
    try {
      result = await new Promise<BridgeResult>(resolve => {
        timeoutHandle = setTimeout(() => { timedOut = true; resolve({ ok: false, code: 'workbench_unavailable', message: 'MCP capability execution exceeded its bounded timeout.' }) }, timeoutMs)
        boundary(request).then(resolve).catch(() => resolve({ ok: false, code: 'workbench_unavailable', message: 'MCP boundary failed without a result.' }))
      })
    } finally { if (timeoutHandle) clearTimeout(timeoutHandle) }
    const completed = now(); const cancelled = request.signal?.aborted || (!result.ok && result.message.toLowerCase().includes('cancel'))
    if (result.ok) { provenance('completed','completed'); return this.finish({ ...base, status: 'completed', output: result.result, metadata: this.metadata(base, started, completed), errors: [], evidence }, events, this.options) }
    const errorCode = timedOut ? 'execution_timeout' : result.code; provenance(cancelled ? 'cancelled' : 'failed', cancelled ? 'cancelled' : 'failed', errorCode); return this.finish({ ...base, status: cancelled ? 'cancelled' : 'failed', metadata: this.metadata(base, started, completed), errors: [{ code: errorCode, message: result.message }], evidence }, events, this.options)
  }
  private metadata(base: { providerId: string; capabilityId: string; operation: string }, started: Date, completed: Date) { return { providerId: base.providerId, capabilityId: base.capabilityId, operation: base.operation, durationMs: Math.max(0, completed.getTime() - started.getTime()) } }
  private finish(result: Omit<McpExecutionResult, 'auditReferences'> & { providerId: string; capabilityId: string }, events: McpExecutionAuditEvent[], options: McpExecutionOptions, denied = false): McpExecutionResult { const occurredAt = (this.options.now ?? (() => new Date()))().toISOString(); events.push({ eventId: crypto.randomUUID(), eventType: denied ? 'execution_denied' : result.status === 'completed' ? 'execution_completed' : result.status === 'cancelled' ? 'execution_cancelled' : 'execution_failed', executionId: result.executionId, dispatchId: result.dispatchId, planId: events[0]?.planId ?? '', validationId: result.validationId, occurredAt, providerId: result.providerId, capabilityId: result.capabilityId, code: result.errors[0]?.code }); recordCapabilityAuditEvent({ eventType: result.status === 'completed' ? 'execution.completed' : 'execution.failed', executionId: result.executionId, planId: events[0]?.planId, providerId: result.providerId, capabilityId: result.capabilityId, occurredAt, ...(result.errors[0]?.code ? { reason: result.errors[0].code } : {}) }, options); writeAudit(events, options); return { ...result, auditReferences: { executionId: result.executionId, dispatchId: result.dispatchId, validationId: result.validationId } } }
}

export function createMcpCapabilityAdapter(options: McpExecutionOptions = {}): McpCapabilityAdapter { return new McpCapabilityAdapter(options) }
